### ISSUE TITLE
New lava sea creatures

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#1016]
the following sea creatures are not listed in the sea creatures section of the site.

[Flaming Worm](https://hypixel-skyblock.fandom.com/wiki/Flaming_Worm)

[Lava Blaze](https://hypixel-skyblock.fandom.com/wiki/Lava_Blaze)

[Lava Pigman](https://hypixel-skyblock.fandom.com/wiki/Lava_Pigman)

**Comment by nstringham** [comment]
Do we know how to make the images that are used in the sea creature section?

**Comment by MartinNemi03** [comment]
> Do we know how to make the images that are used in the sea creature section?

We do, but it's a bit complicated.

**Comment by dukio** [comment]
From discord, from Lea:
> For mobs: I spawned them in a void preset singleplayer world via /summon and used https://github.com/ata4/mineshot to take an isometric screenshot, then keyed out the background
> For NPCs: I used mineskin.org

Wanted to leave this somewhere it can be found easily

**Comment by nstringham** [comment]
this issue is related to https://github.com/SkyCryptWebsite/SkyCrypt/issues/1037
