### ISSUE TITLE
Taming Exp Bugged

### ISSUE THREAD

**Issue by EmrakulTornAeons** [SkyCryptWebsite/SkyCrypt#1032]
**Describe the bug**
Overflow Taming exp ~55m lower then it was a week ago (I believe it is thinks Taming 60 exists)

**Profile/Location**
(https://sky.shiiyu.moe/stats/EmrakulTornAeons/Kiwi)

**Expected behavior**
It should show that I have ~75m overflow
(Sky.lea.moe shows it correctly)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Comment by metalcupcake5** [comment]
fixed in #1031

**Comment by dukio** [comment]
Pretty sure this was fixed in #1031 

If that's not the case please reopen this or let us know
