### ISSUE TITLE
sea creatures

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#1037]
port the following commit from sky.lea
- [x] https://github.com/LeaPhant/skyblock-stats/commit/507ad993fa80bedad099cfc08d39506b3eb0239b

we should also look into these
- [ ] https://github.com/LeaPhant/skyblock-stats/commit/accb0e595996eed575dbd362a14da24a281196e3
- [ ] https://github.com/LeaPhant/skyblock-stats/commit/60725dffe1c13dbdded899b5e69eac186cf2fa02

**Comment by dukio** [comment]
Nether update will also bring new sea creatures (a lot more seems like)...

**Comment by nstringham** [comment]
> Nether update will also bring new sea creatures (a lot more seems like)...

lets hope @LeaPhant will fix it and we can steal there images.

love you Lea :)
