### ISSUE TITLE
Heavy Chestplate Icon not found

### ISSUE THREAD

**Issue by Ekwav** [SkyCryptWebsite/SkyCrypt#1159]
Icon for item with id `HEAVY_CHESTPLATE` https://sky.shiiyu.moe/item/HEAVY_CHESTPLATE is missing.
![image](https://user-images.githubusercontent.com/16632490/154862915-a57b1635-3680-4bd3-a9e7-064441227b9b.png)
Response code is 500

The other pieces are working eg.
https://sky.shiiyu.moe/item/HEAVY_HELMET

Info about the set:
https://hypixel-skyblock.fandom.com/wiki/Heavy_Armor

**Comment by nstringham** [comment]
The item endpoint is not documented and we don't provide support for it or guarantee that it will work. That being said this problem could be indicative of a larger issue so it's worth looking in to.

**Comment by nstringham** [comment]
Also why is this a 500? Shouldn't this be a 400 (probably 404)

**Comment by Ekwav** [comment]
> Also why is this a 500? Shouldn't this be a 400 (probably 404)

Yeah, 404 not found would be more fitting.

**Comment by DuckySoLucky** [comment]
@metalcupcake5
