### ISSUE TITLE
[0.12.3] M7 Update: Armor dyes

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1169]
https://hypixel.net/threads/0-12-3-master-mode-7.4845290/

Armor pieces can be dyed now:
- An icon is added at the beginning of the name, can this break something? (some regex maybe? or somewhere where we parse the item name)
- They should have a line in the lore, if it's missing we should add it
- How do we handle this with textures? should we disable textures for colored armor pieces? wait to see how each texture handles it? 
- Should we add a new "corner" (like the one for recomb items) that displays the color? could be done for exotics too maybe?

**Comment by nstringham** [comment]
2 corners feels like it might be visually noisy

**Comment by nstringham** [comment]
As far as textures are concerned I would say just make it how it would be in game if you had the pack installed

**Comment by DuckySoLucky** [comment]
@metalcupcake5
