### ISSUE TITLE
[0.12.3] M7 Update: New item type(s)

### ISSUE THREAD

**Issue by MartinNemi03** [SkyCryptWebsite/SkyCrypt#1174]
It seems that there are new item types, i.e. `Longsword`, that is apparently dropped from M7.

**Comment by metalcupcake5** [comment]
seems to work fine so far, reopen if other issues appear
![image](https://user-images.githubusercontent.com/43897385/156811559-72fc8eb8-f55f-47f9-8fb0-109b2be20735.png)

**Comment by dukio** [comment]
It works probably due to the fallback with enchants... so if the longsword doesn't have enchants it won't show up in weapons I think
