### ISSUE TITLE
change highest_rarity_sword -> highest_rarity_weapon

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1198]
https://github.com/SkyCryptWebsite/SkyCrypt/blob/2e2e979df68f1f45015df8795b0ba19d68141813/src/lib.js#L1446-L1456

currently we calculate `highest_rarity_sword` and `highest_rarity_bow`...
1. `highest_rarity_bow` is not even used
2. `highest_rarity_sword` is used to display the top weapon... but it only counts for weapons... this doesn't make sense anymore since a bow can be the top tier weapon now, there's wands too and other item types

Proposal:
1. deprecate both `highest_rarity_sword` and `highest_rarity_bow`
2. make `highest_rarity_weapon` (which counts for all weapons displayed in the weapons section)

**Comment by DuckySoLucky** [comment]
@metalcupcake5 added by someone https://github.com/SkyCryptWebsite/SkyCrypt/blob/development/src/lib.js#L1274
