### ISSUE TITLE
Variable name style

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#1205]
variable and constant names are very inconsistent.

we should make a style guide so we can all start doing the same thing

I like using camelCase for variables and constants and using PascalCase for classes and types.

**Comment by dukio** [comment]
For object properties I would suggest snake_case

But yeah I noticed it too... for classes I think we always use PascalCase, variables mostly camelCase but there's some snake_case sometimes

**Comment by dukio** [comment]
Can eslint check these things?

**Comment by nstringham** [comment]
> For object properties I would suggest snake_case

I've never seen that before. any particular reason?

**Comment by nstringham** [comment]
> Can eslint check these things?

It looks like TypeScript eslint can https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/naming-convention.md

**Comment by dukio** [comment]
> > For object properties I would suggest snake_case
> 
> I've never seen that before. any particular reason?

not that I'm aware of... I just see them often around, but camelCase is fine too

**Comment by MartinNemi03** [comment]
> > > For object properties I would suggest snake_case
> > 
> > 
> > I've never seen that before. any particular reason?
> 
> not that I'm aware of... I just see them often around, but camelCase is fine too

Personally I think snake_case would be better for consistency with object properties from Hypixel, so we don't have to just go back and forward between snake_case and camelCase. For variables, I'm a user of snake_case, but I understand using camelCase as it's been used in most of the code.

So I'm suggesting going snake_case for object properties, camelCase for functions and variables, UPPER_CASE for globally defined variables and PascalCase for classes.

**Comment by DuckySoLucky** [comment]
@metalcupcake5
