### ISSUE TITLE
Remove personalized emoji for specific user

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1207]
https://github.com/SkyCryptWebsite/SkyCrypt/blob/8bccc5eade8f96a015dcbc7a23893981a1982907/src/lib.js#L2239-L2241

...why do these things exist 😔

**Comment by nstringham** [comment]
@boblovespi

**Comment by DuckySoLucky** [comment]
@metalcupcake5 got removed, now it's db
