### ISSUE TITLE
API taking too long to update

### ISSUE THREAD

**Issue by StickyRunnerTR** [SkyCryptWebsite/SkyCrypt#1214]
**Describe the bug**

A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).
Even though the site itself updated, the api endpoint (/api/v2/profile/<name>) havent updated for over 45 minutes.

**Profile/Location**

https://sky.shiiyu.moe/api/v2/profile/first_zombie 

**Expected behavior**
The api endpoint should at least update in every 10 minutes or so; not as long as 45 minutes in my example.

**Screenshots**

![image](https://user-images.githubusercontent.com/85073813/158080357-01d76bf6-630a-41f9-b3fe-e70e65e2bf90.png)
A bot i made using the api endpoint after 28 minutes after the user changed his/her guild to Luxury.

![image](https://user-images.githubusercontent.com/85073813/158080397-adf56a48-561c-4710-84bc-1c5f83ccf4a0.png)
The site updating after 5 minutes of the guild change.

**Comment by nstringham** [comment]
Hey @StickyRunnerTR unfortunately this is the intended behavior. The API only updates when someone visits the site. If you need up to date information you should probably use the Hypixel API not the SkyCrypt API

**Comment by StickyRunnerTR** [comment]
The only reason that i use this api endpoint is that this is the only api endpoint that doesnt use an api key which i dont have a static one. What do you suggest?

**Comment by dukio** [comment]
Hypixel API keys are static as far as I know, they only get "blocked" when you go above the rate limit

**Comment by DuckySoLucky** [comment]
@metalcupcake5
