### ISSUE TITLE
API is not up to date with the data

### ISSUE THREAD

**Issue by Myzumi** [SkyCryptWebsite/SkyCrypt#122]
So im currently using the API of the website, if i get something from the api its old af, last thing i got is 4 days old and on the website only 27min old, will this be fixed or is it always gonna be outdated?

**Comment by MartinNemi03** [comment]
Everything from the API is cache only, so it's intended.

**Comment by metalcupcake5** [comment]
^ the api is cache only so it doesn't use our api requests/processing power

**Comment by Myzumi** [comment]
so it will be always outdated?

**Comment by MartinNemi03** [comment]
Yes, only thing we can suggest is to view the profile on SkyCrypt's website to refresh that data.

**Comment by Myzumi** [comment]
well its sad as the hypixel api dosent give that much infomation, i wanted to use this api but i cant really work with outdated data, is it planned to update it in teh future or will it be outdated forever?

**Comment by MartinNemi03** [comment]
To be transparent, we don't know at this moment. It will need some further discussion with the team, but it wouldn't be in the nearest future. Right now, our priority is the main site and it's stability, but we know about the API community around us and how painful Hypixel's API can be.
I would suggest using Slothpixel's skyblock-parser for the time being if you can, it's actually really good.

**Comment by Myzumi** [comment]
Ok thanks for the help
