### ISSUE TITLE
New essence: Crimson

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1244]
![image](https://user-images.githubusercontent.com/2744227/159338180-920abd78-5efd-4b7c-b42a-f2f6211b2fc5.png)

![image](https://sky.shiiyu.moe/head/67c41930f8ff0f2b0430e169ae5f38e984df1244215705c6f173862844543e9d)

**Comment by metalcupcake5** [comment]
added with #1222
