### ISSUE TITLE
Slayer not showing correct level and saying unclaimed slayer rewards

### ISSUE THREAD

**Issue by MeDerpWasTaken** [SkyCryptWebsite/SkyCrypt#125]
**Describe the bug**
Says I have unclaimed slayer rewards when I well, don't, could be a game issue though as I also don't have the recipes even though I meet the XP requirements and I got the level message

**Profile/Location**
https://sky.shiiyu.moe/stats/MeDerpWasTaken/Mango

**Additional Info**
It's the spider and wolf slayer, I killed them using a raider axe

**Expected behavior**
For it to say my proper level and not say I have unclaimed slayer rewards

**Screenshots**
![image](https://user-images.githubusercontent.com/62511835/97628628-f3ef5980-19fa-11eb-8641-9f7ef052b6bd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome
 - Version: OS Version 2004, Browser version 87.0.4280.27 (Official Build) beta (64-bit) (cohort: Beta)

**Smartphone (please complete the following information):**
 - Device: moto e5 play
 - OS: Android 8.0.0
 - Browser: Chrome
 - Version: 86.0.4240.110 (Offical Build) (32-bit)

**Comment by metalcupcake5** [comment]
Have you claimed the rewards? You need to claim them after unlocking them, or it won't count. Your raw api data seems to suggest this.

**Comment by MeDerpWasTaken** [comment]
I've claimed them

**Comment by MeDerpWasTaken** [comment]
This is still happening

**Comment by metalcupcake5** [comment]
It seems to be an api error so I'm gonna close this issue
