### ISSUE TITLE
Small css thing

### ISSUE THREAD

**Issue by Henry-Santa** [SkyCryptWebsite/SkyCrypt#1257]
**Is your suggestion related to a problem? Please describe in detail.**
A clear and concise description of what the problem is.
Hey, when using autofill on the search bar, it turns the background of the bar white 👎 Thats ugly ngl!

**Describe your suggestion**
Just override the default styling for :autocomple and :-webkit-autofill on the input

**Describe alternatives you've considered**
maybe making it autosearch after you autofill but that could be annoying if you misspelled it one time and that is now saved in your cache and when you click on it, it brings up the wrong player

**Additional context**
![image](https://user-images.githubusercontent.com/98135968/160265805-b343c5ca-b458-477f-92e5-75b96cbfd70c.png)
⬆️ What we currently have.
⬇️ What we could have!
![image](https://user-images.githubusercontent.com/98135968/160265834-38af6c09-b924-4fd0-8edf-11eca3c8d309.png)

### Now that ⬆️ is much better
(I typed that out btw to make it look good)

**Comment by metalcupcake5** [comment]
what browser are you using? i dont seem to have this problem on firefox 98.0.2
![image](https://user-images.githubusercontent.com/43897385/160331613-09b632fa-1dc1-4844-b170-cc5032752dc4.png)

**Comment by Henry-Santa** [comment]
Google Chrome, it seems Firefox might have different default styling on :auto-complete? I see that in your image yours gains a blue border after autocompleting. Maybe that is the default styling on FireFox.

**Comment by Henry-Santa** [comment]
``` js
console.log("bump")
```

**Comment by Henry-Santa** [comment]
https://user-images.githubusercontent.com/98135968/164353589-d9303251-a6e4-460a-a152-899e577937c2.mp4

Hey, this is not fixed on chrome

**Comment by Henry-Santa** [comment]
Sorry I realized the date in that video from that website is wrong
but this is still an issue :(

**Comment by dukio** [comment]
It shouldn't, maybe it's not yet merged to production

**Comment by dukio** [comment]
![brave_2022-04-21_18-51-37](https://user-images.githubusercontent.com/2744227/164511254-01c581d2-c4a8-4767-8ce3-0415b4752000.gif)
yep not an issue anymore, let me know if you still see the issue
