### ISSUE TITLE
Add personal bank

### ISSUE THREAD

**Issue by water-is-nice** [SkyCryptWebsite/SkyCrypt#1266]
pls add personal bank so i can see my personal bank

**Comment by dukio** [comment]
Please give this PR a proper title that refers to the issue "Missing personal bank information"

Also link your profile where you have a personal bank please

**Comment by dukio** [comment]
@MartinNemi03 can you rename this issue?

**Comment by DuckySoLucky** [comment]
@metalcupcake5 removed from API due to privacy
