### ISSUE TITLE
Epic tiger double hit % is wrong

### ISSUE THREAD

**Issue by h8re** [SkyCryptWebsite/SkyCrypt#13]
Example: https://sky.shiiyu.moe/stats/CaptainArner/Lemon

**Comment by WarpWing** [comment]
Hello h8re! Thank you for the submission. Could you give more detail on the glitch? For example, perhaps what the correct double hit is supposed to be?

**Comment by h8re** [comment]
> Hello h8re! Thank you for the submission. Could you give more detail on the glitch? For example, perhaps what the correct double hit is supposed to be?

A level 100 epic tiger has a 20%. I believe this is supposed to have a 14.8% chance. I'm not sure if it's all epic levels, or just 74, as the legendary ones seem to be correct.

**Comment by WarpWing** [comment]
Thank you for the info. Our pet specialists @boblovespi  and @metalcupcake5  will handle this issue :D

**Comment by WarpWing** [comment]
This issue is now resolved. Thank you for your cooperation!
