### ISSUE TITLE
Update weights to support new slayer

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1309]
- [ ] Update senither
- [x] Update lilyweight

**Comment by dukio** [comment]
Check senither here:
https://github.com/Senither/Hypixel-Skyblock-Assistant/blob/master/app/src/main/java/com/senither/hypixel/statistics/weight/SlayerWeight.java
or here
https://github.com/Senither/Hypixel-Skyblock-Leaderboard/blob/master/api/src/utils/playerWeightCalculator.js

**Comment by DuckySoLucky** [comment]
@metalcupcake5  weight is outdated and both of devs gave up on developing so u can close this too :shrug:
