### ISSUE TITLE
Only accessories in acc. bag count towards stats now

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1316]
Accessories in inventory don't count anymore

**Comment by dukio** [comment]
We should still ignore duplicates of the same accessory in the acc. bag

**Comment by dukio** [comment]
@MartinNemi03 @metalcupcake5 what do you if we deprecate the "Inactive Accessories" section? Only accessories in the bag count anyway... and you can put them all inside it so I don't really see a reason to show the inactive ones anymore...

**Comment by MartinNemi03** [comment]
> @MartinNemi03 @metalcupcake5 what do you if we deprecate the "Inactive Accessories" section? Only accessories in the bag count anyway... and you can put them all inside it so I don't really see a reason to show the inactive ones anymore...

Only thing I can think of where it would be useful is when you need to take an accessory out of the bag to open it's menu, so I don't think it would be a problem.

**Comment by DuckySoLucky** [comment]
@metalcupcake5
