### ISSUE TITLE
missing stats

### ISSUE THREAD

**Issue by jeo2321** [SkyCryptWebsite/SkyCrypt#1330]
![Capture](https://user-images.githubusercontent.com/100302523/164935261-64a13b21-e0cf-43da-94e3-46b003fccec7.PNG)
![Capture2](https://user-images.githubusercontent.com/100302523/164935497-0c74984d-ae78-421c-954c-fc61f54f715e.PNG)
![Capture1](https://user-images.githubusercontent.com/100302523/164935502-8aae6505-db4b-431c-aa0a-25a8064f85c9.PNG)

All this disappeared one day and I have not changed any api settings

**Comment by MartinNemi03** [comment]
A fix for this was already in development, now it should be live on production.
