### ISSUE TITLE
Update code that gets armor name

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1346]
[src/lib.js#L1348](https://github.com/SkyCryptWebsite/SkyCrypt/blob/92b031c935279627adfb9ed59931395a9fd17ba8/src/lib.js#L1348-L1352)
![image](https://user-images.githubusercontent.com/2744227/166144170-a5c9fe11-a624-4f5b-9253-9e19164eeb4d.png)

This should be updated to include the new dungeon "stars" things, armor dyes, dungeon boss enhancement (this thing: ![image](https://user-images.githubusercontent.com/2744227/166144096-dc860a26-e41e-4176-9dab-3725084a0873.png))

Or better at this point just do a whitelist regex for `A-Za-z0-9 -'`, and `.trim()`

**Comment by StickyRunnerTR** [comment]
instead of regex A-Za-z0-9 -', use \w, far easier imo

**Comment by dukio** [comment]
> instead of regex A-Za-z0-9 -', use \w, far easier imo

`\w` is equivalent to `A-Za-z0-9_`, not `A-Za-z0-9 -`

**Comment by DuckySoLucky** [comment]
@metalcupcake5
