### ISSUE TITLE
Featured profiles don't account for name changes

### ISSUE THREAD

**Issue by MartinNemi03** [SkyCryptWebsite/SkyCrypt#1348]
When a featured profile changes their name ingame, they no longer show up on the frontpage.

**Comment by dukio** [comment]
Is there a reason why the features profiles are in the db and not just a plain frontend object?

**Comment by MartinNemi03** [comment]
> Is there a reason why the features profiles are in the db and not just a plain frontend object?

Not really afaik, I could make it into a public json file while fixing this issue.
