### ISSUE TITLE
Backpack Preview Bug

### ISSUE THREAD

**Issue by Brandonion** [SkyCryptWebsite/SkyCrypt#135]
**Describe the bug**
On a regular backpack, it would show a preview of what's in the backpack. For example: 
![image](https://user-images.githubusercontent.com/72035838/98021662-6d02fe00-1db9-11eb-8325-f93faa2616b2.png)
However, this backpack does not have a preview, picture is in the screenshot section.

**Profile/Location**
https://sky.shiiyu.moe/stats/Pigicial/Lemon
Check the ender chest on the 14th column and the 8 and 9th row.

**Additional Info**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/72035838/98021988-e26ece80-1db9-11eb-9071-ea782d980d96.png)
![image](https://user-images.githubusercontent.com/72035838/98022020-ec90cd00-1db9-11eb-8f93-76d6db98dddf.png)

**Desktop (please complete the following information):**
Windows 10 on chrome browser. Not sure on what version

**Additional context**
It could be a bugged backpack ingame, Im not sure though.

**Comment by Brandonion** [comment]
https://sky.shiiyu.moe/stats/Pigicial/Lemon
The large backpack is still broken

**Comment by metalcupcake5** [comment]
It most likely has nothing in it, which is why it is not displayed
