### ISSUE TITLE
New animated items

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1356]
https://hypixel-skyblock.fandom.com/wiki/Archfiend_Dice
https://hypixel-skyblock.fandom.com/wiki/High_Class_Archfiend_Dice

**Comment by dukio** [comment]
## [High_Class_Archfiend_Dice](https://hypixel-skyblock.fandom.com/wiki/High_Class_Archfiend_Dice)

![4](https://user-images.githubusercontent.com/2744227/167961954-6081c5b1-181e-4aef-86eb-d4f212677d00.png)
![2](https://user-images.githubusercontent.com/2744227/167961955-3aed7b9f-3898-4f70-b457-89e111277c18.png)
![3](https://user-images.githubusercontent.com/2744227/167961956-9e53d437-cf15-4d82-8a3e-9e97384a9596.png)
![1](https://user-images.githubusercontent.com/2744227/167961957-6072507e-3f88-48a5-803a-42a1efea3678.png)
![5](https://user-images.githubusercontent.com/2744227/167961959-3a0b0f0f-8ff2-4c5f-846e-f8dbee9fa9a5.png)

I can't get the 6 😔

**Comment by dukio** [comment]
## [Archfiend_Dice](https://hypixel-skyblock.fandom.com/wiki/Archfiend_Dice)

![1](https://user-images.githubusercontent.com/2744227/168165018-30339dc2-a747-47f2-9a1a-22b60766b17b.png)
![2](https://user-images.githubusercontent.com/2744227/168165020-455ad922-28d4-4162-a251-a920ff8859ab.png)
![3](https://user-images.githubusercontent.com/2744227/168165021-fb3b9d2a-0809-4021-98e1-71da774bf267.png)
![4](https://user-images.githubusercontent.com/2744227/168165022-2bef092d-d443-4238-8652-24b01de88022.png)
![5](https://user-images.githubusercontent.com/2744227/168165024-82d9e240-980d-4adc-9d26-5198e750ae27.png)

**Comment by DuckySoLucky** [comment]
@metalcupcake5
