### ISSUE TITLE
Blaze slayer API error 

### ISSUE THREAD

**Issue by StickyRunnerTR** [SkyCryptWebsite/SkyCrypt#1366]
**Describe the bug**
Blaze slayer's stats dont show up (like enderman slayer) at the api if blaze slayer is never done before

**Profile/Location**
sky.shiiyu.moe/api/v2/profile/mouthshutter5000

**Expected behavior**
blaze tab under slayers' existance

**Screenshots**

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser Firefox

**Additional context**
![image](https://user-images.githubusercontent.com/85073813/166746363-31a44b22-d348-4ccb-a951-cf9547935bf7.png)

**Comment by lochyj** [comment]
Seems to be working fine on my profile... this might have been fixed though. So i suggest closing this issue.
Also the profile link you added doesn't work anymore.
![image](https://user-images.githubusercontent.com/79903111/183076489-0b707b12-03d1-4d6b-87b8-6aead62b7229.png)

**Comment by DuckySoLucky** [comment]
@metalcupcake5
