### ISSUE TITLE
API active_effects

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1382]
![image](https://user-images.githubusercontent.com/2744227/167961282-f455b588-7f84-4a52-91b3-396898acad2d.png)

For front-end stats too?

**Comment by dukio** [comment]
Together with "disabled_potion_effects"

**Comment by dukio** [comment]
Also check what's "paused_effects"? maybe while in dungeons?

**Comment by metalcupcake5** [comment]
active effects do not give stat boots: have to hardcode

**Comment by dukio** [comment]
yeah we need to hardcode the potion@tier = stats bonus :/
