### ISSUE TITLE
Item icon classes stack upon each other in lore preview

### ISSUE THREAD

**Issue by MartinNemi03** [SkyCryptWebsite/SkyCrypt#1397]
Basically can be replicated by hovering over any item and checking icon's classes.
![image](https://user-images.githubusercontent.com/24756921/168448473-d3a1d064-c084-4727-9dab-34cb8b637952.png)

**Comment by dukio** [comment]
Caused by https://github.com/SkyCryptWebsite/SkyCrypt/pull/1349/files#diff-a5323771b78a4cd0e63fe210f1da173cf49fdabfb58b29c10a38913af1c620d7 most likely
Will make a fix later today or tomorrow
