### ISSUE TITLE
Pets

### ISSUE THREAD

**Issue by boblovespi** [SkyCryptWebsite/SkyCrypt#14]
**Describe the bug**
a bunch of pet stats are wrong

**Profile/Location**
check #bug-reports in discord

**Screenshots**
again, check #bug-reports

**Comment by boblovespi** [comment]
@metalcupcake5 can you fix all the pet issues? im busy adding armor abilities

**Comment by FantasmicGalaxy** [comment]
I got this, just give me a day or two

**Comment by WarpWing** [comment]
![image](https://user-images.githubusercontent.com/28925758/91504853-477ae500-e89c-11ea-8fb2-c8b1c3cfa882.png)

**Comment by Shiiyu** [comment]
woah you can upload images here

**Comment by metalcupcake5** [comment]
![image](https://user-images.githubusercontent.com/43897385/91607979-9589fa00-e929-11ea-9309-7890fc62ef1f.png)

**Comment by Shiiyu** [comment]
OMG ITS PROTOGENT

**Comment by apollyon600** [comment]
![image](https://user-images.githubusercontent.com/41652412/91608270-19dc7d00-e92a-11ea-8792-4f8b3cc90648.png)
