### ISSUE TITLE
Mythic Bat Pet

### ISSUE THREAD

**Issue by symt** [SkyCryptWebsite/SkyCrypt#141]
**Describe the bug**
The mythic bat pet doesn't show up on the site. The bat becomes mythic when holding the Vampire Fang item.

**Profile/Location**
https://sky.shiiyu.moe/stats/meyi/Grapes

**Additional Info**
N/A

**Expected behavior**
The bat pet should be mythic when holding the item, and the pet score should be 6 for the pet, not 5.

**Screenshots**
https://imgur.com/a/dbUxHUY

**Comment by MartinNemi03** [comment]
Done with the latest commit.
