### ISSUE TITLE
Dominus special character missing

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1413]
![image](https://user-images.githubusercontent.com/2744227/169825700-d35452d4-c9d8-4d12-8a92-67c7b9faa109.png)

**Comment by dukio** [comment]
![dominus](https://user-images.githubusercontent.com/2744227/169868759-5a62aa59-bad9-41e7-b2da-17d33df2f99c.svg)

**Comment by dukio** [comment]
There's more than this that should be converted to icon font, see Terror armor Hydra Stack and maybe others (overflow mana things?)

**Comment by guarde** [comment]
This has since been fixed - I checked it on multiple browsers :)

**Comment by DuckySoLucky** [comment]
@metalcupcake5
