### ISSUE TITLE
Loving reforge doesn't count towards "AD" in bonus stats in the armor section

### ISSUE THREAD

**Issue by Eonick** [SkyCryptWebsite/SkyCrypt#1419]
**Describe the bug**
I have Wither Goggles (+49.5% AD and Loving reforge chestplate (+5% AD) but total AD in bonus section is 49.5%

**Profile/Location**
https://sky.shiiyu.moe/stats/Eonick/Tomato#Armor

**Additional Info**
Necrotic Recombobulated Wither Goggles and Loving Recombobulated Storm's Chestplate

**Expected behavior**
I don't know if additive or multiplicative but I expected either 54.5% or 52%

**Screenshots**
![image](https://user-images.githubusercontent.com/106236956/170229881-b91db6b9-8b30-471e-85b3-3da585532881.png)
![image](https://user-images.githubusercontent.com/106236956/170229923-c31c860d-e9d6-4f3c-b7ab-62ac947e3c08.png)
![image](https://user-images.githubusercontent.com/106236956/170229961-775bba20-ace2-49fa-a257-b1c660f549d7.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: Latest (Version 101.0.4951.67 on Chrome)

**Comment by dukio** [comment]
Thanks for the report, added this to the list in #1393
