### ISSUE TITLE
iOS item count Z fighting

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#142]
**Describe the bug**
On iOS the item count sometimes is rendered behind the item icon. It also sometimes flickers between being in front of and behind the icon.

**Profile/Location**
https://sky.shiiyu.moe/stats/iijei

**Expected behavior**
Count should always display above icon

**Screenshots**
![IMG_0136](https://user-images.githubusercontent.com/44071655/98932105-e59a4680-24ac-11eb-8ec0-303a585f9706.PNG)

**Tested browser:**
 - Device: iPhone XR
 - OS: iOS 14.2
 - Browser Safari

**credit**
This bug was originally reported by `@Jei#3803` on discord

**Comment by Pottedplant530** [comment]
Does this only happen in landscape mode?

**Comment by Pottedplant530** [comment]
oh nvm i defently see this problem

**Comment by dukio** [comment]
I gave a look and noticed the item texture and the count number both have the same z-index, normally it should work but I imagine this could be what's causing the issue, so this *might* fix the issue:
![image](https://user-images.githubusercontent.com/2744227/101907236-8c602880-3bba-11eb-817c-9603adf2b8dd.png)
(z-index from 15 to 16)

unfortunately I do not own any iOS device to test this on so.... maybe you can test it see if this fixes it?

**Comment by nstringham** [comment]
@dukio thanks I have tested your fix on iOS and it works
