### ISSUE TITLE
Golem pet Third Ability Bug?

### ISSUE THREAD

**Issue by CrushingStar** [SkyCryptWebsite/SkyCrypt#143]
**Describe the bug**
Basically the title of the third ability, "Toss",  doesn't show up(Check screenshot for clarification). Can't confirm it's only me so could just be something on my side.

**Profile/Location**
It happens with every player that has a golem pet.

**Screenshots**
![testing](https://user-images.githubusercontent.com/69564686/99618621-a6f61600-29ef-11eb-8389-032d8fbc9a0d.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.198

**Comment by metalcupcake5** [comment]
Fixed with https://github.com/SkyCryptWebsite/SkyCrypt/commit/ea604793af43f83fb671abac124fef7f2bc75a45
