### ISSUE TITLE
the site doesn't show the defense you're getting from baby yeti

### ISSUE THREAD

**Issue by Nobiluga** [SkyCryptWebsite/SkyCrypt#144]
**Describe the bug**
with the baby yeti every strength point of yours become to defense and i don't see it in the site.
im in the game with around 1700 defense but i see only 600 in the site.

**Profile/Location**
just an example: https://sky.shiiyu.moe/stats/Nobiluga/Zucchini  (put yeti)
that's what i have in game
![image](https://user-images.githubusercontent.com/74715496/99664087-4bb83800-2a70-11eb-9d1f-70ca31a89789.png)

**Additional context**
it's not really an issue or bug, it's more like a missing calculation

**Comment by MartinNemi03** [comment]
Yeah, if it adds it as an extra percentage, then it's not added as one of our devs hasn't completed that feature yet, so we're aware of that.

**Comment by boblovespi** [comment]
closing because i think we already fixed this - open it again if we haven't
