### ISSUE TITLE
API bank_account (private bank in coops?)

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1458]
I'm not in a coop but:
![image](https://user-images.githubusercontent.com/2744227/172703949-1231eb73-fb5f-466e-b1ab-cf6cec4279aa.png)

from: 
https://github.com/HypixelDatabase/HypixelTracking/commit/12531393bbc1f89b53d007050874f1d7f447263b

It most likely displays the "personal bank" of a coop member, it's the same as global banking object for solo players

**Comment by DuckySoLucky** [comment]
@metalcupcake5 removed from API due to privacy
