### ISSUE TITLE
API personal_bank_upgrade

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1464]
![image](https://user-images.githubusercontent.com/2744227/172707472-9f95b77b-1e64-46e6-ad65-465f8d7c8501.png)

We can know the max amount the bank can hold?

**Comment by DuckySoLucky** [comment]
@metalcupcake5 added in https://github.com/SkyCryptWebsite/SkyCrypt/pull/1927
