### ISSUE TITLE
MongoDB error 

### ISSUE THREAD

**Issue by Soapdevs** [SkyCryptWebsite/SkyCrypt#1497]
**Describe the bug**
I keep getting this mongoDB error I've tried whitelisting my ip on mongoDB and it still wont work

**Error Log**
MongoServerSelectionError: connection <monitor> to 52.20.9.178:27017 closed
    at Timeout._onTimeout (C:\Users\PC\Downloads\SkyCrypt-development\SkyCrypt-development\node_modules\mongodb\lib\sdam\topology.js:306:38)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'cluster0-shard-00-00.kx9xv.mongodb.net:27017' => ServerDescription {
        _hostAddress: HostAddress {
          isIPv6: false,
          host: 'cluster0-shard-00-00.kx9xv.mongodb.net',
          port: 27017
        },
        address: 'cluster0-shard-00-00.kx9xv.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 7396352,
        lastWriteDate: 0,
        error: MongoNetworkError: connection <monitor> to 52.20.9.178:27017 closed
            at Connection.onClose (C:\Users\PC\Downloads\SkyCrypt-development\SkyCrypt-development\node_modules\mongodb\lib\cmap\connection.js:138:19)
            at Socket.<anonymous> (C:\Users\PC\Downloads\SkyCrypt-development\SkyCrypt-development\node_modules\mongodb\lib\cmap\connection.js:65:46)
            at Socket.emit (node:events:527:28)
            at TCP.<anonymous> (node:net:709:12) {
          [Symbol(errorLabels)]: Set(0) {}
        }
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {}
}

**Developer Tools**

- Node.js version: v16
- OS: Windows 10

**Comment by nstringham** [comment]
Did you configure the mongo URL in config.json?

**Comment by Soapdevs** [comment]
> Did you configure the mongo URL in config.json?

I've put my mongo url in credentials.json but not config.json, Can you tell me which directory is the config.json in

**Comment by nstringham** [comment]
> > Did you configure the mongo URL in config.json?
> 
> I've put my mongo url in credentials.json but not config.json, Can you tell me which directory is the config.json in

You did the right thing I just forgot what the file was called sorry

**Comment by Soapdevs** [comment]
> 

How do I fix this error then?

**Comment by nstringham** [comment]
I'm not sure. I always use the cloud mongo personally. @WarpWing you have some DevOps experience do you have any ideas?

**Comment by WarpWing** [comment]
I have been summoned! I'll check it out.

**Comment by WarpWing** [comment]
Is this a self-hosted instance or a free MongoDB atlas instance?

**Comment by WarpWing** [comment]
In addition @KyleTheDev, this is a public instance? I can ping it and even attempt to make a connection to it. I would recommend not exposing DB IPs.

**Comment by Soapdevs** [comment]
> Is this a self-hosted instance or a free MongoDB atlas instance?

Its a atlas instance

**Comment by WarpWing** [comment]
@KyleTheDev have you tried connecting with the URL instead of basic credentials?

**Comment by Soapdevs** [comment]
> @KyleTheDev have you tried connecting with the URL instead of basic credentials?

Can you tell me which URL please I'm kinda new to mongodb and stuff

**Comment by WarpWing** [comment]
> > @KyleTheDev have you tried connecting with the URL instead of basic credentials?
> 
> Can you tell me which URL please I'm kinda new to mongodb and stuff 

The URL for the DB that you put in the credentials.json file

**Comment by Soapdevs** [comment]
Fixed
