### ISSUE TITLE
Missing talismans bug

### ISSUE THREAD

**Issue by Pottedplant530** [SkyCryptWebsite/SkyCrypt#150]
**Describe the bug**
If you click on a talisman it is supposed to show the lore. But if you click on a talisman in the missing section it grays the background but there's now lore. A proposed change to this is either don't let you click on them or have them show the talismans base lore.
**Profile/Location**
Happens on any profile without every talisman so ill just link mine https://sky.shiiyu.moe/stats/pottedplant530/Papaya

**Additional Info**
N/A

**Expected behavior**.
Listed at beginning
**Screenshots**
![image](https://user-images.githubusercontent.com/74434901/99805484-a1d9b980-2b0a-11eb-9149-c27db85b2fa2.png)

**Desktop (please complete the following information):**
 - OS: windows 10 [e.g. iOS]
 - Browser chrome [e.g. chrome, safari]
 - Version IDK  [e.g. 22]

**Comment by MartinNemi03** [comment]
This is the expected behavior, since we only give it info about name, texture and rarity. So this is not a bug, but is something to be improved into the future.

**Comment by Pottedplant530** [comment]
Alright thanks
