### ISSUE TITLE
Social Skill Leveling

### ISSUE THREAD

**Issue by Farman52** [SkyCryptWebsite/SkyCrypt#1519]
The Social level on the SkyCrypts website doesn't match with my ingame Social level.
I've done some research on how the social skill leveling works because it felt kind of odd for me and found out that Hypixel stores only the player's social xp, that means if you are in a coop and someone visits you through your coopmate (/visit coopmate) then the XP doesn't add under your profile in SkyBlock Public API, but rather adds under your coopmate's profile in the API.
So you have to loop through every coop member until you get all the Social XP from the specific coop profile
![unknown (8)](https://user-images.githubusercontent.com/32415385/175833484-bbad29fc-4bf0-4c22-9c5c-63480fa9e6bc.png)
![unknown (7)](https://user-images.githubusercontent.com/32415385/175833485-0edbd9df-bd35-4ef2-8df5-5fb3b4f1499f.png)

**Comment by dukio** [comment]
Thanks for reporting, I noticed this some time ago but always forgot to write it down...

Yeah for some weird reason coops have an advantage in social skills compared to solo profiles... so we need to sum the social skill of all members 😕
