### ISSUE TITLE
Way of requesting data deletion.

### ISSUE THREAD

**Issue by MHFDoge** [SkyCryptWebsite/SkyCrypt#1544]
**Is your suggestion related to a problem? Please describe in detail.**
I have had no less than 4 people contact me while ingame about purchasing an item in my inventory. Upon further investigation as to how people keep finding this information(as I have had that part of the API disabled for over a year now, and your site is still displaying an old version of that data. I would like to know if there is a way that this information can be removed from your service to prevent further unwanted contact from random people.

**Describe your suggestion**
Some menu or button to request the removal of your profile's data from the service.

**Comment by metalcupcake5** [comment]
could i have a link to the profile?

**Comment by MartinNemi03** [comment]
Wait, the inventory data is still viewable even after disabling it for a year? That's weird, it definitely shouldn't be like this.
I suppose you can message us on our Discord for now while we look into API settings and possibly preventing similar issues in the future. _On that note, hi metal._

**Comment by MHFDoge** [comment]
https://sky.shiiyu.moe/stats/MHF_Doge/Apple#Armor

I'm also confused as to how it just updated that information(it shows my armor is empty which it is, because I removed the items earlier). Am I misunderstanding what this setting means? Or is this an issue on hypixel's end?
![unknown-145.png](https://user-images.githubusercontent.com/46448580/178124934-b9359e94-7ee5-498a-ad73-91a992ad017d.png)

**Comment by nstringham** [comment]
@MHFDoge are you remembering that the API settings are profile specific? So you will need to disable the API in each of the profiles that you would like hidden.

**Comment by MHFDoge** [comment]
I didn't realize it was per profile but after hearing that it makes sense that it would be. I'm pretty sure that's set on the profile in question as off but I'll double check that in a few minutes and try to pin something down.

**Comment by MHFDoge** [comment]
It appears that earlier I must have hit the button to enable that information being shared, probably with the intention to force a purge, and forgot about it, which would explain why it updated. The setting was off before though, I know that for certain. I've emptied my inventory on the profile this issue is with of all but one item. Would you be able to force an update of that information? After that I'll turn the setting back off and give it time to see if it happens again. Sorry for this mess.

**Comment by nstringham** [comment]
> Would you be able to force an update of that information?

Hypixel itself only updates the API every 3 minutes and we only cash data for 7 minutes so it should go away on its own within 10 minutes.

**Comment by MHFDoge** [comment]
Ah, gotcha. Thank you, it appears it's updated now and it's not showing the inventory data with the setting off(as intended)

I swear it was off before I opened this issue, my only guess is that it took me cycling the setting to get something to update, possibly on hypixel's end. The reason for it doing that is beyond me but it's fixed now. Thank you for your help and once again, sorry if I sound like a rambling idiot 😂.

**Comment by nstringham** [comment]
I'm glad to hear it's working as expected for you now. Let us know if you have any other problems.
