### ISSUE TITLE
Fix spelling mistake in comment on line 645

### ISSUE THREAD

**Issue by ajarvis-3** [SkyCryptWebsite/SkyCrypt#1549]
https://github.com/SkyCryptWebsite/SkyCrypt/blob/788b1c365f1eee29dd831bc1fface808697e1290/public/resources/ts/stats-defer.ts#L645

Please fix the spelling mistake on line 645:

> *wether* the document currently has a smooth scroll taking place

**Comment by metalcupcake5** [comment]
real @nstringham  moment

**Comment by nstringham** [comment]
> real @nstringham moment

I don't understand how you know I had anything to do with this
