### ISSUE TITLE
ERROR User not found in selected profile. This is probably due to a declined co-op invite.

### ISSUE THREAD

**Issue by MichiTW** [SkyCryptWebsite/SkyCrypt#1562]
**Describe the bug**
I invited my friend to my island before ,but he left the coop soon after. This make skycrypt can’t find his profile after that , and it is annoying that it will occupy one slot in the website display even there is nothing in the profile (I mean 8756 not ImM1ChI) . But it won’t display the player in my main account. Could you guys help me to solve the problem? Like remove the not found player, I will be very grateful ;)

**Profile/Location**
My main : SmartMiChI
https://sky.shiiyu.moe/stats/SmartMiChI/Apple

My multiple account : ImM1ChI
https://sky.shiiyu.moe/stats/ImM1ChI/2d201334a95a49ad8eed3963c2f1ef17

My friend’s account : 8756
https://sky.shiiyu.moe/stats/5a337d276e41478ca07a45690cfa4e11/2d201334a95a49ad8eed3963c2f1ef17

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**

**Screenshots**
![62468E8F-8424-4F74-A071-EE3E2A04ADB8](https://user-images.githubusercontent.com/109405890/180909042-d27bd761-54aa-4fc9-bd84-24cc17697928.png)
![A00CFE34-7DBB-43D4-8D21-556ED92E6583](https://user-images.githubusercontent.com/109405890/180909056-076b9b4f-d4cd-4d9b-b9f9-0d3e380d0ada.png)
![C48C599A-4355-47CD-B042-100FA8968ACA](https://user-images.githubusercontent.com/109405890/180909051-b950c672-22b2-4995-ab28-cb852c9fd79f.png)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [chrome]
- Version [latest]

**Smartphone (please complete the following information):**

- Device: [iPhone12]
- OS: [iOS15.4]
- Browser [stock browser, safari]
- Version [latest]

**Additional context**

**Comment by nstringham** [comment]
I noticed that you didn't fill out the "Expected behavior" section. What do you think SkyCrypt "should" be doing in this case?

I haven't looked into this particular case yet but Issues like this are often problems with hypixel and not with SkyCrypt itself

**Comment by MichiTW** [comment]
Sorry for my omission. I just hope u to use something like scanning system
to clean up the empty profile, because I want to make it look neat.
I know that sounds silly, but I just don’t want people searching my profile
to see the occupy slot, It ruins the beauty.

Nate Stringham ***@***.***>於 2022年7月27日 週三，00:21寫道：

**Comment by nstringham** [comment]
> I just hope u to use something like scanning system to clean up the empty profile

That sounds like a potential solution but before we talk about solutions let's make sure we agree on what the problem is.

Do you think that your alt shouldn't show on your profile?

Do you think that 8756 shouldn't show on their profile?

Once we have identified specific issues we can try to figure out what causes those issues and how to fix them.

**Comment by MichiTW** [comment]
Yes, I agree. No thx ;) He hasn’t even played with this profile, so that is
what I’m talking about He is "occupying" the profile slot, and hope he
disappears.

Nate Stringham ***@***.***>於 2022年7月27日 週三，04:50寫道：

**Comment by nstringham** [comment]
Is he on the profile? The purpose of SkyCrypt is to display accurate information about Hypixel Skyblock so if he is on the profile then SkyCrypt is working as intended.

**Comment by MichiTW** [comment]
No, it's not. But he joined coop briefly and left, so  the bug happened
,and hope you could clear that
slot.
Nate Stringham ***@***.***>於 2022年7月27日 週三，08:19寫道：

**Comment by nstringham** [comment]
Is the API correct and this is a SkyCrypt problem? Or is SkyCrypt correct and this is a problem with the Hypixel API

**Comment by MichiTW** [comment]
No, it doesn't. I think that It’s SkyCrypt's bug because The profile had
been existed ,but SkyCrypt couldn’t find that ;)

Nate Stringham ***@***.***>於 2022年7月27日 週三，18:36寫道：

**Comment by lochyj** [comment]
I just took a look at the profile and it seems to have been fixed, this could be because it was an issue with the Hypixel API and not Skycrypt.
So i would assume this was a one time thing.

**Comment by MichiTW** [comment]
Great, thanks!
Yeah I invited 8756 again then Skyblock canceled the invitation ,so his
slot was gone. Anyway Still thank u <3

Lachlan Jowett ***@***.***>於 2022年8月5日 週五，20:12寫道：

**Comment by nstringham** [comment]
It sounds like this is resolved
