### ISSUE TITLE
New enchants

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1583]
Champion X
Hecatomb X

https://hypixel.net/threads/august-5-chili-pepper-update.5057174/

**Comment by metalcupcake5** [comment]
most likely would be same data as stuff like expertise yes?

**Comment by dukio** [comment]
> most likely would be same data as stuff like expertise yes?

Yes

**Comment by metalcupcake5** [comment]
added with #1629

**Comment by dukio** [comment]
Still needs to be added to the max enchants array
