### ISSUE TITLE
0.14 - Carpentry is now a skill

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1602]
It gives +hp for each level
Since it's an official skill, it should count towards Skill Avg and weight calculations... problem is it's not in achievements API? or maybe it is now? needs to be checked

https://hypixel.net/threads/skyblock-patch-0-14-shens-auctions-the-hex-rng-meter-and-more.5074247/

**Comment by metalcupcake5** [comment]
https://github.com/LeaPhant/skyblock-stats/compare/742c04e5c7...f8ddd73c22
