### ISSUE TITLE
0.14 - New stats / stats changes

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#1603]
https://hypixel.net/threads/skyblock-patch-0-14-shens-auctions-the-hex-rng-meter-and-more.5074247/

> The stats menu(s) available in "your profile menu" has been upgraded to show where all of your stats are from.
> If you want to learn more about it, [here's an objectively mediocre guide about it](https://www.youtube.com/watch?v=KgcY8bNsoKk).
> New Stats:
7 Wisdom Stats for different skills, which increase skill XP gain. (For example, Slayer now grants Combat Wisdom!)
Fishing Speed
Health Regen
Vitality, which boosts incoming healing (good for tanks!)
Mending, which boosts outgoing healing (good for healers!)
Fishing Speed also works differently as before. It used to remove a % of the remaining time available to spawn the fish, the system now simply adds a value and it linearly makes the particles spawn faster.
If you reach 300 Fishing Speed, the particles will appear instantly, but there is an exception with the Crimson Isle, where 350 Fishing Speed is the value you have to reach for maximum efficiency.

**Comment by DuckySoLucky** [comment]
@metalcupcake5
