### ISSUE TITLE
New Enrichments show separately despite being the same type 

### ISSUE THREAD

**Issue by CShe4p** [SkyCryptWebsite/SkyCrypt#1652]
**Describe the bug**
A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).
Today I enriched a new talisman (recombed Seal of the Family) with Crit Damage. On Skycrypt it is currently showing I have "Enrichments: 23× Critical Damage 1× Critical Damage". Newly enriched Talismans appear to be being classified differently
**Profile/Location**
A link to the profile which the bug occurred with, if applicable
https://sky.shiiyu.moe/stats/combatsheep4/Cucumber#Accessories
**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.
Recombed Seal of the family with a crit damage enrichment
**Expected behavior**
Bug breaking up the list of enrichemnts, should simply show "Enrichments: 24× Critical Damage"
**Screenshots**
![image](https://user-images.githubusercontent.com/113316464/189553521-50cb8e36-cdc7-4286-b33a-bbef0e90e932.png)

Desktop, Windows 11, Chrome, Most recent version of skycrypt

**Comment by metalcupcake5** [comment]
old
![image](https://user-images.githubusercontent.com/43897385/189567020-e5573992-e7f7-420b-973f-05562d016996.png)
new
![image](https://user-images.githubusercontent.com/43897385/189567045-1d6da6a0-673e-42f0-b049-360802095fba.png)
thank you hypixel
