### ISSUE TITLE
Trophy fishes

### ISSUE THREAD

**Issue by JPelle-dot** [SkyCryptWebsite/SkyCrypt#1688]
Suggestion: add a trophy fish section to see what trophy fishes someone has

In the hypixel api, trophy fishes are provided, meaning it should definetely by in skycrypt. I would suggest to give the full trophy rank (bronze, silver, gold, diamond) and then a table with all the different trophy fish

**Comment by DuckySoLucky** [comment]
Hey! Trophy Fish section is currently in progress, check #1665 for more information

**Comment by metalcupcake5** [comment]
#1665 as ducky said for pr, #1462 for relevant issue
