### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by konoashi** [SkyCryptWebsite/SkyCrypt#17]
For the moment your website is only turned on player api but why not add new tabs with skyblock news (like cowshed: https://discord.gg/bPNw4gF) or maybe create minigames like dragon/slayer/zealots simulator or calculator for dungeons item/damages/magic damages/minions/talismens... I have begin to made dragon simulator and dungeon calculator, you can take if you want/need (https://github.com/BagginsOrga/FabulousWebSite) Thank you for reading

**Comment by WarpWing** [comment]
Thank for the suggestion! We are currently working on stabilizing the website so it can handle the traffic accordingly. On a personal note, this is a bomb idea so I'm going to discuss this when I next ping spam the entire dev team <3.

**Comment by WarpWing** [comment]
I'm actually going to close this for now but we will come back to it <3
