### ISSUE TITLE
PET_SKIN_BLACK_CAT_PURRANORMAL

### ISSUE THREAD

**Issue by DuckySoLucky** [SkyCryptWebsite/SkyCrypt#1706]
> https://hypixel.net/threads/spooktacular-halloween-2022.5129719/

![image](https://user-images.githubusercontent.com/75372052/194153600-02dbe00a-ca4b-4489-bb7a-82db5100340b.png)
![purranormal-skin](https://user-images.githubusercontent.com/75372052/194153605-708987bf-9025-4195-9d90-c20879b80381.gif)

**Comment by dukio** [comment]
There's 2 more new skins in the shop too
