### ISSUE TITLE
mm7 dragon visible in Last Dragon Kills

### ISSUE THREAD

**Issue by ZDibLO** [SkyCryptWebsite/SkyCrypt#1707]
**Describe the bug**
Dragon last kills also shows how many master wither king dragons you killed lmao

**Profile/Location** https://sky.shiiyu.moe/stats/DeathStreeks*/main profile*)

**Additional Info**

**Expected behavior**
It shouldnt count / show master wither king dragon kills

**Screenshots**
![Screenshot_20221005-220745_Chrome.jpg](https://user-images.githubusercontent.com/101671735/194155140-46f002a7-a169-4310-b971-574fddb28e58.jpg)

**Desktop (please complete the following information):**

Samsung Galaxy 10s
- OS: Android 10
- Browser App / Opera GX / KHTML 5.0, like gecko
- Version Unkown

**Smartphone (please complete the following information):**

- Bruh didnt saw that

**Additional context**
Funny that it counts mm7 dragons lmao

**Comment by nstringham** [comment]
Thanks @ZDibLO
