### ISSUE TITLE
API for coins does not give the "Bank" in the JSON

### ISSUE THREAD

**Issue by wolfieboy09** [SkyCryptWebsite/SkyCrypt#1711]
**Describe the bug**
When I sent a request for the "COINS" part, the "bank" in the JSON is not in the JSON. The "bank" is in the API docs. I even checked google, and sure enough, "bank" is not included.

**Profile/Location**
My status: https://sky.shiiyu.moe/stats/Wolfieboy09/Strawberry
Project: https://replit.com/@wolfieboy09/PySky?v=1

**Additional Info**
API

**Expected behavior**
In the API docs, for coins, the API should return with "purse" and "bank". The API returns with "purse" but not the "bank"

**Screenshots**
![Screenshot 2022-10-09 12 45 17 PM](https://user-images.githubusercontent.com/105564186/194769096-3c07302d-4aee-43b8-b0b7-8912a00546eb.png)
![image](https://user-images.githubusercontent.com/105564186/194769169-bea2a062-ff43-48af-a572-7d4f251f65ab.png)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]
- Version [??]
- I'm running it on Replit currently

**Additional context**

**Comment by DuckySoLucky** [comment]
@wolfieboy09 the bank is not shown because player has Banking API off. 
Example:
https://sky.shiiyu.moe/api/v2/coins/DeathStreeks
![image](https://user-images.githubusercontent.com/75372052/194769331-12e423ed-58ba-4e34-8ebc-57d35deeddbe.png)

**Comment by wolfieboy09** [comment]
I was told that, and now I am going to chect it @DuckySoLucky
