### ISSUE TITLE
Sorry not a suggestion, I had a question but wasn't sure where to ask. So I wanted to know the config for the packs because it looks different when I put the packs into my game!

### ISSUE THREAD

**Issue by iCraft85** [SkyCryptWebsite/SkyCrypt#1722]
So I saw that SkyCrypt items were from different packs and wanted to know how this was done. I tried just stacking the packs but it didn't give me the same result, is there like an edited version of the pack thats being used?

**Comment by DuckySoLucky** [comment]
> So I saw that SkyCrypt items were from different packs and wanted to know how this was done. I tried just stacking the packs but it didn't give me the same result, is there like an edited version of the pack thats being used?

Heya, so the Default pack is mix of all packs, highest priority has FurfSky if I'm not mistaken

**Comment by iCraft85** [comment]
@DuckySoLucky Ty, and can I know what the rest of the priorities are? 
Or is there somewhere I can find the priorities?

**Comment by DuckySoLucky** [comment]
> @DuckySoLucky Ty, and can I know what the rest of the priorities are? Or is there somewhere I can find the priorities?

Sorry no ;-;

**Comment by metalcupcake5** [comment]
yes actually, the priorities are in the config file of each pack - see the [resource pack readme](https://github.com/SkyCryptWebsite/SkyCrypt/blob/development/public/resourcepacks/README.md), very bottom
![image](https://user-images.githubusercontent.com/43897385/196254151-4accb3b3-d9ee-45e5-9e6c-0952847e0235.png)

**Comment by dukio** [comment]
@iCraft85 literally 98%+ of textures you see in default pack are from furfsky... I would suggest to just use that pack and you probably won't ever notice anything different

**Comment by DuckySoLucky** [comment]
@metalcupcake5
