### ISSUE TITLE
Refactor: Split stats.ejs into multiple section files

### ISSUE THREAD

**Issue by MartinNemi03** [SkyCryptWebsite/SkyCrypt#1737]
I feel like with the way we're currently going, the main stats.ejs file is slowly becoming unmaintainable. 

I would suggest splitting the EJS file into seperate files based on the sections (Armor, Pets etc.) and do that over a certain span until we're done with the splitting and all PRs are on the new splitted files.

**Comment by DuckySoLucky** [comment]
@metalcupcake5

**Comment by DuckySoLucky** [comment]
@metalcupcake5
