### ISSUE TITLE
Blank screen for certain profiles and miscalculation of magical power

### ISSUE THREAD

**Issue by louislevar** [SkyCryptWebsite/SkyCrypt#1739]
https://sky.shiiyu.moe/stats/nokbwastaken
https://sky.shiiyu.moe/stats/z86

On my profile and my friend's profile, it shows a white screen upon being loaded. Also, another thing is that when my API was showing, it said my magical power was 400 when it was in fact 374.

Browser - Brave Browser + Chrome
OS - macOS Big Sur

Additional Info:
Earlier today only my friend's profile was blank and mine was showing, now they are both blank.

The page I am met with
<img width="405" alt="Screenshot 2022-10-27 at 9 17 57 PM" src="https://user-images.githubusercontent.com/105536611/198295133-a2e27847-b3ed-4338-a290-7e0a96ce7112.png">

**Comment by xmorose** [comment]
Can confirm.

**Comment by DuckySoLucky** [comment]
@MartinNemi03 / @metalcupcake5 Can you close this issue? It has been resolved, forgot to mention it in PR ;-;

**Comment by metalcupcake5** [comment]
fixed in #1741
