### ISSUE TITLE
Current tag shows as false for all profiles

### ISSUE THREAD

**Issue by Su386yt** [SkyCryptWebsite/SkyCrypt#1742]
Current tag shows as false for all profiles no matter which one is selected in the API.

Platform: API

Example: 
`` "14b9f9d1b3a542c786ec7e19976ced3c": {
            "profile_id": "14b9f9d1b3a542c786ec7e19976ced3c",
            "cute_name": "Peach",
            "current": false,``
``"372129ee06084cac9d030e11cc2ea896": {
            "profile_id": "372129ee06084cac9d030e11cc2ea896",
            "cute_name": "Cucumber",
            "current": false,``
``"d25951d79430472eac31b8415f7ae203": {
            "profile_id": "d25951d79430472eac31b8415f7ae203",
            "cute_name": "Grapes",
            "current": false,``

`` "dd24c995aeb34e26abba851237970650": {
            "profile_id": "dd24c995aeb34e26abba851237970650",
            "cute_name": "Tomato",
            "current": false,``

**Comment by DuckySoLucky** [comment]
Thank you for bringing this issue to our attention. Expect a developer to make a PR within the first 3-5 business days of issue submission.
