### ISSUE TITLE
All bank interest

### ISSUE THREAD

**Issue by DaiFaIlSerio** [SkyCryptWebsite/SkyCrypt#1746]
**Is your suggestion related to a problem? Please describe in detail.**
A clear and concise description of what the problem is.
Ex. [...] doesn't work, [...] solves it.

**Describe your suggestion**

**Describe alternatives you've considered**
Ex. [...] could be a problem, but [...]

**Additional context**
Add any other context or screenshots about the suggestion here.

**Comment by DaiFaIlSerio** [comment]
how i can see all my bank interest

**Comment by LeaPhant** [comment]
This isn't possible, bank history is limited to transactions from the past 7 days.
