### ISSUE TITLE
Extreme GPU usage

### ISSUE THREAD

**Issue by Julienraptor01** [SkyCryptWebsite/SkyCrypt#1754]
**Describe the bug**
going on https://sky.shiiyu.moe lead to enormous GPU usage
it makes the iGPU usage 100% when on my built-in screen to it and 30% dGPU usage on my external screens (it can even go further if i continuously scroll up and down)
(+100% iGPU usage too when connected to my externals screens but it's due to my pc not having a mux and by so having to forward all data through the iGPU)

**Profile/Location**
Everywhere on any profile

**Additional Info**
I'm pretty sure it's related to the character & item rendering since when character is on screen it continuously take the same amount and drop back to 0 when it's not visible
The fact scrolling increase it even more make me think that item rendering is badly done too

**Expected behavior**
Either a normal GPU usage and a way to disable the thing that cause this massive usage

**Screenshots**
![image](https://user-images.githubusercontent.com/49841713/198984157-d144c1cd-6ac1-4a15-83f9-6abefe7e219f.png)

**Desktop :**

(Tested on my 2 PCs and lead to the same results)
- OS : Windows 10
- Browser : Firefox, Chrome
- Version 106.0.2, 107.0.5304.88

**Smartphone :**

- Device : Didn't test
- OS : Didn't test
- Browser : Didn't test
- Version : Didn't test

**Additional context**
Here's a more lightweight skin renderer
https://github.com/bs-community/skinview3d
Item rendering needs to be fixed too
An idea to fix this is render once then cache the result and use this cache instead of re-rendering each time

**Comment by Julienraptor01** [comment]
Here's a screenshot of the test with on chrome where the only tab open is your website
![image](https://user-images.githubusercontent.com/49841713/198987239-4bab7be0-f5df-49c9-9f16-021f1d5fa25c.png)
Here's the raw performance of my pc with everything closed so you have a comparison point
![image](https://user-images.githubusercontent.com/49841713/198987357-342fb197-496b-4ced-978f-eda300b085e2.png)
And i've just noticed that CPU usage is really bad too
I'm nearly wondering if you aren't mining when the website is open
(this last sentence is a joke don't take it too seriously but the whole issue is a BIG problem)

**Comment by Julienraptor01** [comment]
A better version of the lightweight skin renderer
https://github.com/cosmetica-cc/skinview5d

**Comment by MartinNemi03** [comment]
We really need to take a look at the site's performance as a whole, since you're not the first one reporting this behavior with either high CPU and/or GPU usage and also there are general performance issues we're definitely not happy with. This will be a long roadtrip ahead, but I hope we'll be able to come up with some solutions.

Thanks for the skin renderer suggestion, we'll have a look at it as well.

**Comment by DuckySoLucky** [comment]
@metalcupcake5 close or no, you choose. Nothing we can really do here except full rewrite :man_shrugging:
