### ISSUE TITLE
Api Profile bug

### ISSUE THREAD

**Issue by thecookieswhoplays** [SkyCryptWebsite/SkyCrypt#1762]
**Describe the bug**
When I use this irl https://sky.shiiyu.moe/api/v2/profile/lecookieplayer
it gives me that
{
"error": "Cannot read properties of undefined (reading 'special_0')"
}

**Expected behavior**
To return a player's profile

**Screenshots**
![image](https://user-images.githubusercontent.com/96542139/200470056-5ea70ca1-6022-4aec-8eee-571f5f483d5d.png)

**Desktop (please complete the following information):**

windows 10
chrome Version 107.0.5304.88 (Official Build) (64-bit)

**Comment by DuckySoLucky** [comment]
> **Describe the bug** When I use this irl https://sky.shiiyu.moe/api/v2/profile/lecookieplayer it gives me that { "error": "Cannot read properties of undefined (reading 'special_0')" }
> 
> **Expected behavior** To return a player's profile
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/96542139/200470056-5ea70ca1-6022-4aec-8eee-571f5f483d5d.png)
> 
> **Desktop (please complete the following information):**
> 
> windows 10 chrome Version 107.0.5304.88 (Official Build) (64-bit)

Hello, we're currently aware of this bug. There's currently PR #1758 which fixes that. Thanks for your patience
