### ISSUE TITLE
Stats aren't working properly 

### ISSUE THREAD

**Issue by Artinator11** [SkyCryptWebsite/SkyCrypt#180]
**Describe the bug**
At the top of the page if you hover your cursor over the stats the person has (eg: Intelligence, Health, Defence) the box which is supposed to appear describing that persons stats sometimes appears pointing to different stats then the one your cursor is on.

**Profile/Location**
https://sky.shiiyu.moe/stats/Artinator11/Papaya

**Expected behaviour**
What I expected to happen was the box to appear and the stats to appear in the right place.

**Screenshots**
![image](https://user-images.githubusercontent.com/71243393/101856610-c0871980-3bb9-11eb-9f29-df972ff33193.png)
![image](https://user-images.githubusercontent.com/71243393/101856656-d8f73400-3bb9-11eb-9e49-9e546dfa29d3.png)
![image](https://user-images.githubusercontent.com/71243393/101856659-dac0f780-3bb9-11eb-83b7-0189fed923f4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 10

**Comment by metalcupcake5** [comment]
Seems like this is only happening with intel

**Comment by metalcupcake5** [comment]
I believe this was fixed in #161
