### ISSUE TITLE
SkyBlock Levels Display?

### ISSUE THREAD

**Issue by Gadet-0** [SkyCryptWebsite/SkyCrypt#1816]
> **Is your suggestion related to a problem? Please describe in detail.**

No

> **Describe your suggestion**

Allow users to see the skyblock level (as of 0.15 SkyBlock Update) progression/display above the player skills tab

> **Describe alternatives you've considered**
Ex. [...] could be a problem, but [...]

No?

> **Additional context**
Add any other context or screenshots about the suggestion here.

No?

**Comment by DuckySoLucky** [comment]
Hey! Skyblock levels aren't currently in the Hypixel API. Levels are actually planned to be added to the Hypixel API in the future. We will do our best to incorporate it into SkyCrypt as soon as it becomes available. In the meantime, we appreciate your patience and understanding.
