### ISSUE TITLE
Item value on pets missing

### ISSUE THREAD

**Issue by doej1367** [SkyCryptWebsite/SkyCrypt#1854]
**Describe the bug**
All items have an item value and also all categories have a networth.
Except for pets - there the item value isn't shown even though they count towards the networth.

(Also very cool that networth is a thing now 🎉)

**Profile/Location**
https://sky.shiiyu.moe/stats/thirtyvirus/Kiwi

**Expected behavior**
The Item value to be shown like everywhere else

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 109.0.1

**Comment by DuckySoLucky** [comment]
Heya! Oops, must have missed that, thanks for letting me know

**Comment by doej1367** [comment]
Done already. Nice!

One more small thing though: The other items have `one line space` between the last entry and the line with the `Item Value:`. Just in case someone cares about a consistent layout... 

Also: Do pets not have an `Obtained:` date?

**Comment by DuckySoLucky** [comment]
> Done already. Nice!
> 
> One more small thing though: The other items have `one line space` between the last entry and the line with the `Item Value:`. Just in case someone cares about a consistent layout... 
> 
> Also: Do pets not have an `Obtained:` date?

Okay, gonna fix that. Not sure I don't believe that they do, gonna add if they do

**Comment by DuckySoLucky** [comment]
Added spacing, but `Obtained:` cannot be added since it's not in the item NBT. Pets have following NBT data:
![image](https://user-images.githubusercontent.com/75372052/218143994-cabf0f50-7d6a-4011-bc1e-d5f84f2ee938.png)

**Comment by doej1367** [comment]
Just came up with an idea: **How about a "per backpack value sum"?**
Maybe even go a step further and replace the constant item value for backpacks by the sum for the contents?

![grafik](https://user-images.githubusercontent.com/19228364/219964261-a876bb03-fa9a-45c0-85ec-472778940d02.png)

**Comment by DuckySoLucky** [comment]
> Just came up with an idea: **How about a "per backpack value sum"?** Maybe even go a step further and replace the constant item value for backpacks by the sum for the contents?
> 
> ![grafik](https://user-images.githubusercontent.com/19228364/219964261-a876bb03-fa9a-45c0-85ec-472778940d02.png)

Planned
