### ISSUE TITLE
Add experimentation info

### ISSUE THREAD

**Issue by konoashi** [SkyCryptWebsite/SkyCrypt#186]
![image](https://user-images.githubusercontent.com/64316846/102013423-666c8c80-3d50-11eb-8251-293e3e827959.png)

**Comment by metalcupcake5** [comment]
1. This is planned
2. How is this an issue?

**Comment by nstringham** [comment]
@metalcupcake5 it is customary to use issues for feture requests that is what the enhancement tag is for.

**Comment by metalcupcake5** [comment]
oh sorry, maybe i should make a template
