### ISSUE TITLE
Bazaar API returning some Russian characters?

### ISSUE THREAD

**Issue by Nahmuun** [SkyCryptWebsite/SkyCrypt#189]
When pulling data from the https://sky.shiiyu.moe/api/v2/bazaar URL, The Item Ids:
LOG:2,
ROTTEN_FLESH,
SULPHUR,
GLOWSTONE_DUST
all have their item names as Russian characters. 

Eg:

LOG:2 - Береза
ROTTEN_FLESH - Гнилая плоть
SULPHUR - Порох
GLOWSTONE_DUST - Светопыль

https://sky.shiiyu.moe/api/v2/bazaar

I expected for the names to be 
LOG:2 - Birch  Wood
ROTTEN_FLESH - Rotten Flesh
SULPHUR - Gunpowder
GLOWSTONE_DUST - Glowstone Dust

 - OS: Windows
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

I have tried to refresh several times, nothing has changed. It has been an hour, and the characters are still the same. It is not just a one-off thing.

**Comment by MartinNemi03** [comment]
That's on Hypixel's side, we only take what we get from them every 1-2 minutes and give that to our endpoints.. If this isn't solved by them, we could look into alternative solutions of solving this problem later.

**Comment by Nahmuun** [comment]
So, should I Report this on the Hypixel website? Or is it a known bug?

**Comment by MartinNemi03** [comment]
> 
> 
> That's on Hypixel's side, we only take what we get from them every 1-2 minutes and give that to our endpoints.. If this isn't solved by them, we could look into alternative solutions of solving this problem later.

Update: After some investigation, it's actually problem on Slothpixel's side, which is where we get item info from.

**Comment by MartinNemi03** [comment]
That makes our possible solution easier. We'll contact @builder-247 about this. Thanks for reporting this to us.
