### ISSUE TITLE
Bug Report: duplicate talismans

### ISSUE THREAD

**Issue by Leobastian04** [SkyCryptWebsite/SkyCrypt#19]
You might already know this, but opening the missing Talisman menu Shows all Missing talismans, including downgrades of already owned Talisman, Like Pot affinity ring/talisman, Speed affinity talisman/ring, scarfs xxx(the Dungeon Xp boost one), Slayer defense talismen and rings, Red claw Ring/Talisman and some Other i might have missed, although i own the maxed version. Really Happy you included a "Missing Talisman" Feature though, thats one Thing i Always missed in skylea

**Comment by metalcupcake5** [comment]
This is intentional, I merged this version into master. I just wanted to release it bcs it was taking a while. Expect a fix soon!

**Comment by metalcupcake5** [comment]
Fixed #26
