### ISSUE TITLE
Error when trying to check my profile.

### ISSUE THREAD

**Issue by Mustario** [SkyCryptWebsite/SkyCrypt#1913]
**Describe the bug**
I get the error that can be seen in my screenshot only whentryng to check my profile. It doesnt happen when i try other profiles and ive tried at least 10.

**Profile/Location**
**Expected behavior**
Id expect to be able to see my profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/41838181/228365131-bf530fb7-10d2-4124-9c8a-706bf32a0a8b.png)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser Vivaldi
- Version idk where i can check that on this browser

**Smartphone (please complete the following information):**

- Device: S21fe
- OS: Android 13
- Browser chrome

**Additional context**
Another weird bug that happes on my phone is that when trying to check my profile the verification keeps going in a loop(im talking about the check if youre a robot thingy). Ive tried to do it multiple times and it also happens only on my profile. At the moment i get the same error i get on my pc so i cant send a screenshot.

**Comment by DuckySoLucky** [comment]
Fixed by #1902, not in production yet

**Comment by DuckySoLucky** [comment]
Regarding
> Another weird bug that happes on my phone is that when trying to check my profile the verification keeps going in a loop(im talking about the check if youre a robot thingy). Ive tried to do it multiple times and it also happens only on my profile. At the moment i get the same error i get on my pc so i cant send a screenshot.

That's due to cloudflare we cannot do anything about that

**Comment by Mustario** [comment]
alright thank you idk if i should close the issue or not so you do it

**Comment by DuckySoLucky** [comment]
> alright thank you idk if i should close the issue or not so you do it

Better close it, so solved issues don't stack up
