### ISSUE TITLE
Lotus equipment appear as farming tools in the Farming Tools section

### ISSUE THREAD

**Issue by katazina0** [SkyCryptWebsite/SkyCrypt#1915]
![image](https://user-images.githubusercontent.com/92119647/228834112-7451ef76-aa44-4568-8ad8-b82b182d13e5.png)

Haven't tested / seen other equipment other than cloak, but it seems that it could be due to the Green Thumb enchantment.

**Comment by DuckySoLucky** [comment]
> ![image](https://user-images.githubusercontent.com/92119647/228834112-7451ef76-aa44-4568-8ad8-b82b182d13e5.png)
> 
> Haven't tested / seen other equipment other than cloak, but it seems that it could be due to the Green Thumb enchantment.

Yeah, it's due to Green Thumb enchantment, thank you for report

**Comment by katazina0** [comment]
Also, personally, I don't think that non-Anita tools should be included in this list, as they're somewhat irrelevant, with a debatable exception of Rookie Hoe and copper tools like Advanced Gardening Axe and Hoe. You can't see it in the screenshot, but a treecap is included in the list as well, as it has the Sunder enchantment on it. Let me know what you think about it

**Comment by DuckySoLucky** [comment]
> Also, personally, I don't think that non-Anita tools should be included in this list, as they're somewhat irrelevant, with a debatable exception of Rookie Hoe and copper tools like Advanced Gardening Axe and Hoe. You can't see it in the screenshot, but a treecap is included in the list as well, as it has the Sunder enchantment on it. Let me know what you think about it

Well thing is, there might be someone who maxed his golden axe for pumpkin farming instead of using pumpkin dicer since it gives no benefit except more experience. So yeah, I get what you mean but not sure tbh :shrug:
