### ISSUE TITLE
Skycrypt Loading Bug

### ISSUE THREAD

**Issue by JihnFPS** [SkyCryptWebsite/SkyCrypt#1920]
When I open skycrypt I get a "verify you are a human" box and when i click it, it loads for like 30 seconds and then refreshes the page and makes me verify again.

Every Profile

![Screenshot 2023-04-05 005122](https://user-images.githubusercontent.com/71983045/229984050-2c37366e-33c1-460f-a091-5ec764b9b382.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome
- Version idk

**Comment by metalcupcake5** [comment]
this is a problem with cloudflare, not on our side
