### ISSUE TITLE
Custom Item Textures fails to load when using certain syntax

### ISSUE THREAD

**Issue by ic22487** [SkyCryptWebsite/SkyCrypt#1932]
## The Bug
Properties Files that use regex or pattern syntax
(`regex:(BONZO_STAFF|STARRED_BONZO_STAFF)`  `pattern:Runaan*s Bow`)
or NBT outside of ExtraAttributes and display 
(`nbt.SkullOwner.Properties.textures.0.Value=`)
do not load

## Profile
https://sky.shiiyu.moe/stats/ic22487/Pineapple

## Additional Info
*There are tons of items affected by this, so here are some easy items you can check to see the bug in action:*

**NBT outside of ExtraAttribtes and display**
- Abiphones (FurfSky Reborn)

**Pattern Syntax**
- Runaan's Bow (FurfSky Reborn)
- Midas' Sword (FurfSky Reborn)

**Regex Syntax**
- Campfire Badges
- Wedding Rings (Hypixel Plus)
- Trapper Crest (Hypixel Plus)

## Expected behavior
These items appear as they normally do in game, instead of as their vanilla counterparts

## System Environment
macOS Ventura 13.3.1
Safari 16.4

**Comment by Zickles** [comment]
Is this still a bug? If so i can take a look when i get home.

**Comment by Zickles** [comment]
Just checked this is still a bug will look into it
