### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by PChallenges** [SkyCryptWebsite/SkyCrypt#1940]
When I go to the website for Skycrpyt and i am unable to get anything I just get a 404 Not Found Error

**Comment by xblacky11** [comment]
> When I go to the website for Skycrpyt and i am unable to get anything I just get a 404 Not Found Error

Hypixel API Issue

**Comment by jani270** [comment]
> > When I go to the website for Skycrpyt and i am unable to get anything I just get a 404 Not Found Error
> 
> Hypixel API Issue

The Hypixel API is fine:

![image](https://user-images.githubusercontent.com/69345714/234592151-a13eac30-6d65-4ee6-ba0c-4597ece3d14f.png)

**Comment by DuckySoLucky** [comment]
@metalcupcake5
