### ISSUE TITLE
Little error with the display of owned accessory and magical Power

### ISSUE THREAD

**Issue by DerTamile** [SkyCryptWebsite/SkyCrypt#1948]
A Friend of mine found out that the display of accessory's and the breakdown of accessory's for the calculation of the magic power don't add up if you have the same accessory multiple times in different rarity's like recombed and non recombed deletor's  
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/133385212/15bb81fb-ab90-453c-8fea-8095f37ac373)

so basically the total count and the break down have wrong values which weird
i dont have the know how so i should not say to much 

but i believe its because of the fact that both accessory's are in the wrong place 
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/133385212/d654e4bb-56de-4ead-9b82-07ee90afbc94)
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/133385212/06dd078c-3b16-4087-bd4b-71f5c4c555d5)

(For references his acc: https://sky.shiiyu.moe/stats/Freddi004/Kiwi#Accessories) 
I am not used to Github and i just made my account so i can report this bug if this has already been reported sry for wasting your time 

thanks for your work
-some skyblock player

**Comment by DuckySoLucky** [comment]
Fixed in https://github.com/SkyCryptWebsite/SkyCrypt/pull/1898
