### ISSUE TITLE
Mobile UI can be Scrolled horizontally

### ISSUE THREAD

**Issue by Kathund** [SkyCryptWebsite/SkyCrypt#1949]
**Describe the bug**
UI can be Scrolled to the right because the search bar is too long

**Profile/Location**
any

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
With an old screenshot that I found in the files it has the search done correctly and you cannot scroll across
![android-1.jpg](https://github.com/SkyCryptWebsite/SkyCrypt/assets/55346310/3b6e11a5-af46-4e72-815b-87ad12fa4dfe)

**Screenshots**
![Screenshot_20230526-182105.png](https://github.com/SkyCryptWebsite/SkyCrypt/assets/55346310/ba12d5f4-50df-474d-9190-37615ad489d7)

**Smartphone (please complete the following information):**
- Device: Google pixel 5
- OS: Android 13
- Browser: Tested with brave and stock chrome 
- Version: Brave - 1.51.118 Chrome 113.0.5672.162

**Additional context**

**Comment by DuckySoLucky** [comment]
#1405 Dupe

**Comment by Kathund** [comment]
Closed due to dupe
