### ISSUE TITLE
stats bug

### ISSUE THREAD

**Issue by brax009** [SkyCryptWebsite/SkyCrypt#1951]
**Describe the bug**
some of the stats aren't syncing up with my in game stats   

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**

**Screenshots**
![game1](https://github.com/SkyCryptWebsite/SkyCrypt/assets/134972233/ade6fe36-a6b4-4aad-85e8-0b8f3d91ebf7)
![game2](https://github.com/SkyCryptWebsite/SkyCrypt/assets/134972233/e4cbe029-7f2e-4eea-a4ac-623db6f0626a)

**Desktop (please complete the following information):**

- OS:  Windows 10
- Version 1.19.4

**Comment by Zickles** [comment]
pretty sure there was a problem with health and other things affected by skyblock levels. i think there is a pull request open to fix it it just hasnt been merge yet

**Comment by DuckySoLucky** [comment]
> pretty sure there was a problem with health and other things affected by skyblock levels. i think there is a pull request open to fix it it just hasnt been merge yet

Yeah, there's PR. Sadly it's not possible to fully sync stats due to API limitations

**Comment by Zickles** [comment]
#1696
