### ISSUE TITLE
Vampire Slayer Tab Bugged

### ISSUE THREAD

**Issue by GreeningSiren** [SkyCryptWebsite/SkyCrypt#1969]
**Describe the bug**
Vampire Slayer Tab Div is messed up and positioned wrongly!

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)
https://sky.shiiyu.moe/stats/RodNon/Mango#Slayer                    // or any other stats page on tab Slayer //

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.
He has Unclaimed Slayer Rewards

**Expected behavior**
To look like the other slayer tab things

**Screenshots**
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/75137978/6a0d078c-f039-4d53-877e-387fdca4a672)

**Desktop (please complete the following information):**

- OS: Windows 10 ver 22h2
- Browser Opera GX

**Additional context**
It's messed up pls fix!

**Comment by DuckySoLucky** [comment]
@metalcupcake5 close this
