### ISSUE TITLE
skill icons missing in firefox

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#197]
**Describe the bug**
on firefox the skill icons are missing

**Profile/Location**
any

**Expected behavior**
Icons show up like they do on chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/44071655/103384930-41a14480-4ac6-11eb-966b-021f9d8c67cd.png)

**Desktop:**
 - OS: Windows 10
 - Browser firefox
 - Version 84.0.1

**Note**:
seams to be working fine on android firefox 85

**Comment by metalcupcake5** [comment]
Seems to work for me, Windows 10 firefox 84.0.1

**Comment by nstringham** [comment]
I don't know what caused it or fixed it but it is working now
