### ISSUE TITLE
Floats improperly cut on pet XP

### ISSUE THREAD

**Issue by Zenthi** [SkyCryptWebsite/SkyCrypt#1970]
When viewing pet XP progress to the next level, the total required XP to the next level, if  shortened (ie thousands or millions), is improperly cut off and goes to 10 decimal places.
![Screenshot 2023-06-28 011408](https://github.com/SkyCryptWebsite/SkyCrypt/assets/137993836/cd020970-35ba-4c49-aeb5-8e528f2faf0c)

![Screenshot 2023-06-28 011444](https://github.com/SkyCryptWebsite/SkyCrypt/assets/137993836/72f2daec-8755-4558-98e3-907dda604d01)

**Comment by Zickles** [comment]
Don’t think ducky made a pr yet will make one in.2-3 hours

**Comment by DuckySoLucky** [comment]
@metalcupcake5 can you close this?
