### ISSUE TITLE
ERRORCannot read properties of null (reading 'glowing')

### ISSUE THREAD

**Issue by ErickNavaAldana** [SkyCryptWebsite/SkyCrypt#1972]
**Describe the bug**
A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).
ERRORCannot read properties of null (reading 'glowing') when trying to access certain profile

**Profile/Location**
https://sky.shiiyu.moe/stats/EbassMiner/Pomegranate

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DuckySoLucky** [comment]
Fixed in #1954 
@metalcupcake5 close this
