### ISSUE TITLE
Optional checklist for maximum fortunes of various skills (QoL)

### ISSUE THREAD

**Issue by AwesumnessJon** [SkyCryptWebsite/SkyCrypt#1978]
This isn't related to a problem, but is more of a quality of life suggestion. Essentially, it would just make it easier to track how close a player is to the maximum possible fortune for a skill, and what items they would need to achieve it.

Similar to how there is a missing accessories and missing pets dropdown, I believe a great addition to the website would be a dropdown showing which items or upgrades players currently do not own which would contribute to the maximum possible fortune stat for the different skills (e.g. farming, mining, foraging). This could work similarly to the missing accessories and missing pets dropdown and showing enchantments needed as enchanted books. In the descriptions shown by hovering over the tiles, the website would list how much fortune the item would contribute, and enchantments/reforges listing which items they would need to be applied to. Additionally, the best pet with the optimal held item would also be listed.

This is just intended to be a quality of life feature for players intending to maximize their efficiency when grinding a skill, and would be especially helpful for farmers seeking to maximize their loadout. Not a necessary feature, but would be nice to have.

**Comment by DuckySoLucky** [comment]
was actually planned, but due to API limitations sadly it's not possible. Technically it is but calculation is gonna miss like 40% of stuff

**Comment by AwesumnessJon** [comment]
Dang, that sucks. Would have been a cool feature to have.

**Comment by DuckySoLucky** [comment]
@metalcupcake5 close this too I guess, since it's not really possible and showing not correct data isn't really something we should do
