### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by CreatieDrones** [SkyCryptWebsite/SkyCrypt#1983]
Cloudflare systems are down
meaning the website
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/122066046/ab3640f7-bb55-4ee6-bd58-7cbc3964ec9d)

- OS: Windows 11
- Browser opera GX/firefox

**Comment by DuckySoLucky** [comment]
@metalcupcake5

**Comment by CreatieDrones** [comment]
Already online again
