### ISSUE TITLE
[type:api] Gear stats not showing when requesting armor/wardrobe/weapons from API

### ISSUE THREAD

**Issue by Eclipixie** [SkyCryptWebsite/SkyCrypt#1989]
**Describe the bug**
Damage, strength, health, defense etc stats are empty when requesting weapon/armor/wardrobe data from Skycrypt API.

**Profile/Location**
Applies to all profiles. I'm requesting data from [here](https://docs.google.com/spreadsheets/d/16JICu6Cf-HLAO5Zra0aMMQoa2Ttfv2NXfAJG1h6LesA/edit?usp=sharing)

**Additional Info**
N/A

**Expected behavior**
Weapon stats should be visible in column E of the "Gear" sheet. (it looks like it's populated since the enchants column is overflowing into it)

**Screenshots**
![Screenshot 2023-08-03 9 36 10 AM](https://github.com/SkyCryptWebsite/SkyCrypt/assets/85773134/89a483aa-e07f-4677-95c2-6b7d987d625f)

Edit: Just for the record, I haven't actually taken a look at the raw data yet, so sorry in advance if this is just Google Sheets being Google Sheets.
Edit 2: Checked data at the URL I'm requesting from (sky.shiiyu.moe/api/IGN/Profile/weapons?html), and there is in fact no column relating to weapon stats, only weapon ID, weapon name, rarity, enchants and upgrades.
Edit 3: making sure I'm not accidentally triggering markdown formatting

**Comment by DuckySoLucky** [comment]
> Damage, strength, health, defense etc stats are empty when requesting weapon/armor/wardrobe data from Skycrypt API.

Your browser does the calculation so API returns just base values, this was done due to performance issues, calculation can be found at https://github.com/SkyCryptWebsite/SkyCrypt/blob/development/public/resources/ts/calculate-player-stats.ts

**Comment by DuckySoLucky** [comment]
Also could you please join discord so we can talk it's gonna be faster and easier, I'm not really sure what you mean

**Comment by Eclipixie** [comment]
> > Damage, strength, health, defense etc stats are empty when requesting weapon/armor/wardrobe data from Skycrypt API.
> 
> Your browser does the calculation so API returns just base values, this was done due to performance issues, calculation can be found at https://github.com/SkyCryptWebsite/SkyCrypt/blob/development/public/resources/ts/calculate-player-stats.ts

I'll take a look at that. TYSM for the link!

**Comment by Eclipixie** [comment]
> Also could you please join discord so we can talk it's gonna be faster and easier, I'm not really sure what you mean

Will do once I get home.

**Comment by DuckySoLucky** [comment]
@metalcupcake5
