### ISSUE TITLE
Information Not Showing

### ISSUE THREAD

**Issue by GrandPaRob** [SkyCryptWebsite/SkyCrypt#199]
**Describe the bug**
When I use the site and search anyone's name, the site would work like usual but the player's skin won't show up and if I click on a item e.g livid dagger, ender dragon pet etc, it would only show a white outline around the box and the information like pet exp and enchants wouldnt show.
**Profile/Location**
all profiles i search up
**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
I expected to see my character/other people's character and also expected to see information when i click on a item/pet

**Screenshots**
https://cdn.discordapp.com/attachments/776317726540431380/794852350660968448/character_doesnt_show.png
https://cdn.discordapp.com/attachments/776317726540431380/794852418424537118/clicking_on_item_doesnt_give_info.png

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Chrome
 - Version: 78

**Smartphone (please complete the following information):**
 - Device: ZTE Axon A1R
 - OS: Android 6.0.1
 - Browser: Chrome
 - Version: 87

**Additional context**

**Comment by metalcupcake5** [comment]
Could you open the console and post any errors? I believe the shortcut for chrome is Ctrl+Shift+J

**Comment by nstringham** [comment]
@GrandPaRob is this problem occuring on your phone and your Windows PC?

Also try updating Chrome on your PC you're using a old version that might be causing some problems

**Comment by GrandPaRob** [comment]
@nstringham this problem occurs on the PC only

**Comment by GrandPaRob** [comment]
@metalcupcake5 here is a picture https://cdn.discordapp.com/attachments/776586248785625108/796594171871363082/for_person.png

**Comment by nstringham** [comment]
@GrandPaRob have you tried updating Chrome I really think that might help your problems.

**Comment by GrandPaRob** [comment]
@nstringham I have tried to update chrome, but it doesn't say checking for updates when I try to update it in the settings

**Comment by nstringham** [comment]
@GrandPaRob it sounds like you have a problem with Chrome here is the official trouble shooting guide for Google Chrome update problems https://support.google.com/chrome/answer/111996

**Comment by GrandPaRob** [comment]
@nstringham I have deleted chrome and installed it again but it still does not work

**Comment by nstringham** [comment]
@GrandPaRob what version of chrome is it now? and is the error in the console the same?

**Comment by GrandPaRob** [comment]
@nstringham It is version 78 and the error is still the same

**Comment by nstringham** [comment]
@GrandPaRob That's the same version as last time can you please update to Chrome 86 or higher

**Comment by Artinator11** [comment]
The same thing happens to me sometimes on chrome, my Chrome version is 87 I think its something to do with the page not loading

**Comment by metalcupcake5** [comment]
hmmm this should've been fixed a couple days ago

**Comment by nstringham** [comment]
@Artinator11 if this is still a problem please do the keyboard shortcut Ctrl+Shift+J to open the console and let us know if there are any error messages there

**Comment by GrandPaRob** [comment]
@nstringham I have tried to update it, but the update thing doesn't show up so I can't update it

**Comment by nstringham** [comment]
@GrandPaRob this is not a problem with SkyCrypt here are your options:
- contact Chrome support for help updating Chrome https://support.google.com/chrome/a/answer/4594885?hl=en
- switch to Firefox https://www.mozilla.org/en-US/firefox
- switch to Edge https://www.microsoft.com/en-us/edge

**Comment by nstringham** [comment]
@metalcupcake5 I recommend closing this issue

**Comment by metalcupcake5** [comment]
👍
