### ISSUE TITLE
Missing Account

### ISSUE THREAD

**Issue by SoapSudss** [SkyCryptWebsite/SkyCrypt#2001]
Whenever I try to search up my profile on skycrypt, MeLuvPenguins, the account is deemed missing and I have checked on other websites that my info was available but just not on Skycrypt, I have tried on multiple devices but it just didn't show.

https://sky.shiiyu.moe/stats/MeLuvPenguins

I just want my account to be able to be seen on Skycrypt as it is a huge resource for sb players

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome
- Version: 115.0.5790.170 (Official Build) (64-bit) (cohort: 115_170 Stable Control(A))

I have tried accessing my profile on multiple browsers (Chrome, microsoft edge, firefox, opera gx and so on)

**Comment by DuckySoLucky** [comment]
> while the site itself is not broken, it's possible some players might not searchable.
this is due to current issues with an API we use for resolving UUIDs from usernames.
current workaround is just using player's UUID instead of their username.

@metalcupcake5
