### ISSUE TITLE
Bestiary is Empty, all stats are zero.

### ISSUE THREAD

**Issue by DiamondBr3aker** [SkyCryptWebsite/SkyCrypt#2006]
**Describe the bug**
A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).
All bestiary stats are at 0 following the new bestiary update.
**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)
Any profile shows zero, but here is mine:
https://sky.shiiyu.moe/stats/DiamondBr3aker/Pomegranate#Bestiary
**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.
N/A
**Expected behavior**
Accurately reflects the bestiary in Skyblock.
**Screenshots**
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/100955194/bac06a58-d9df-4398-ba71-6a8bb138957d)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Microsoft Edge
- Version 115.0.1901.203

**Additional context**

**Comment by metalcupcake5** [comment]
will be fixed with #1996
