### ISSUE TITLE
Rift race never shows as completed

### ISSUE THREAD

**Issue by TheDGOfficial** [SkyCryptWebsite/SkyCrypt#2007]
**Describe the bug**
Rift race never shows any tiers as completed.

**Profile/Location**
For example, open https://sky.shiiyu.moe/stats/DeathStreeks/Blueberry#Misc and scroll down a bit to the Races section. You'll see each of it having filled circle meaning all race tiers are completed, except the Rift, all circles are empty inside.

**Additional Info**
N/A

**Expected behavior**
Expected the race to be shown as completed (the circles having white filled inside them)

**Screenshots**
![Screenshot from 2023-08-20 02-30-25](https://github.com/SkyCryptWebsite/SkyCrypt/assets/24778409/037ce708-fe29-41c6-a6e5-cb49e8d2c2d9)

**Desktop (please complete the following information):**

- OS: Ubuntu 23.04
- Browser: Firefox Developer Edition 117.0b9

**Additional context**
N/A

**Comment by DuckySoLucky** [comment]
Fixed in #2010, not really proper fix but that's the best we can do because Hypixel didn't add all data to API
