### ISSUE TITLE
Missing Pets shows Montezuma

### ISSUE THREAD

**Issue by TheDGOfficial** [SkyCryptWebsite/SkyCrypt#2008]
**Describe the bug**
Missing Pets should not show Montezuma, as this pet is not obtainable outside of Rift to my knowledge.

**Profile/Location**
For example, go to https://sky.shiiyu.moe/stats/DeathStreeks/Blueberry#Pets and scroll down and click Missing Pets to expand the Missing Pets menu and notice it says Montezuma.

**Additional Info**
N/A

**Expected behavior**
Expected Missing Pets to not show a unobtainable pet.

**Screenshots**
![Screenshot from 2023-08-20 02-35-38](https://github.com/SkyCryptWebsite/SkyCrypt/assets/24778409/a3fd61e2-8412-4ea2-8736-9d86f90b14c1)

**Desktop (please complete the following information):**

- OS: Ubuntu 23.04
- Browser: Firefox Developer Edition 117.0b9

**Additional context**
N/A

**Comment by metalcupcake5** [comment]
fixed in #1980
