### ISSUE TITLE
Shows Missing enrichment for Hocus-Pocus Cipher

### ISSUE THREAD

**Issue by TheDGOfficial** [SkyCryptWebsite/SkyCrypt#2009]
**Describe the bug**
In the Accessories section, SkyCrypt shows 1x Missing Enrichment! because of Hocus-Pocus Cipher. This talisman can't be enriched. The lore text says can't be reforged incorrectly instead of can't be enriched.

**Profile/Location**
For example, go to https://sky.shiiyu.moe/stats/DeathStreeks/Blueberry#Accessories and scroll down a bit to the Enrichments text and notice it says 1x Missing Enrichment!

**Additional Info**
The talisman can be recombobulated but can't be enriched. When i tried myself I think it said something along the lines of you can't use anvil with this item, I don't fully remember though.

**Expected behavior**
Expected accessories that can't be enriched to not show as missing enrichment.

**Screenshots**
![Screenshot from 2023-08-20 02-43-26](https://github.com/SkyCryptWebsite/SkyCrypt/assets/24778409/99e84bca-ed9e-45bf-806e-23f4ae761df7)
![Screenshot from 2023-08-20 02-43-37](https://github.com/SkyCryptWebsite/SkyCrypt/assets/24778409/f625e090-e8cd-4ed7-bc02-095574839d8e)

**Desktop (please complete the following information):**

- OS: Ubuntu 23.04
- Browser: Firefox Developer Edition 117.0b9

**Additional context**
N/A

**Comment by DuckySoLucky** [comment]
Fixed in #1987
