### ISSUE TITLE
Wont let me enter username (ign)

### ISSUE THREAD

**Issue by WonderPig9** [SkyCryptWebsite/SkyCrypt#2016]
**Describe the bug**
I search for my user WonderPug232
When I hit search and the page loads it changes it to wonderpug232

![Uploading F81516B9-C6B0-4498-830C-52D1A7AF6755.png…]()

- Device: IPhone 11
- OS: IOS 15.7.1
- Browser Firefox
- Version 116.4

**Comment by DuckySoLucky** [comment]
@metalcupcake5

**Comment by DuckySoLucky** [comment]
@metalcupcake5 ;-:
