### ISSUE TITLE
Invalid JSON response body

### ISSUE THREAD

**Issue by SirArchibald97** [SkyCryptWebsite/SkyCrypt#202]
**Describe the bug**
When fetching any data using your player endpoint, I get this error when trying to parse the response.

**Profile/Location**
https://sky.shiiyu.moe/api/v2/profile/sirarchibald97

**Additional Info**
I can send requests from my browser perfectly fine, it's just parsing the response in Node which returns the error. I am using the npm package Node-Fetch.

**Expected behavior**
I should be able to parse the data from JSON into a JavaScript object, as I can with all other APIs that return JSON.

**Screenshots**
```
UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://sky.shiiyu.moe/api/v2/profile/[19]%20SirArchibald97 reason: Unexpected token < in JSON at position 0
2021-01-03T16:06:09.291399+00:00 app[worker.1]:     at /app/node_modules/node-fetch/lib/index.js:272:32
2021-01-03T16:06:09.291400+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-03T16:06:09.291400+00:00 app[worker.1]:     at async Object.run (/app/methods/nick.js:35:32)
2021-01-03T16:06:09.291475+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2021-01-03T16:06:09.291581+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: n/a

**Comment by metalcupcake5** [comment]
Using axios seems to work fine
![image](https://user-images.githubusercontent.com/43897385/103487927-aa860680-4dbd-11eb-801f-a860b776d166.png)
I'll try to use node-fetch

**Comment by metalcupcake5** [comment]
Just tried with node-fetch, same response. May I see your code?

**Comment by Tydo690** [comment]
It might be because the URL it's pointing to in your error looks like:
https://sky.shiiyu.moe/api/v2/profile/[19]%20SirArchibald97
and not
https://sky.shiiyu.moe/api/v2/profile/SirArchibald97

**Comment by SirArchibald97** [comment]
> It might be because the URL it's pointing to in your error looks like:
> [https://sky.shiiyu.moe/api/v2/profile/[19]%20SirArchibald97](https://sky.shiiyu.moe/api/v2/profile/%5B19%5D%20SirArchibald97)
> and not
> https://sky.shiiyu.moe/api/v2/profile/SirArchibald97

At first I thought this was the issue as well, but I then tested it with the hardcoded URL and it gave the same error. However, I reinstalled Node-Fetch into a new project and the error seems to have vanishsed now. I may have been using a broken version of the package.

**Comment by SirArchibald97** [comment]
> It might be because the URL it's pointing to in your error looks like:
> [https://sky.shiiyu.moe/api/v2/profile/[19]%20SirArchibald97](https://sky.shiiyu.moe/api/v2/profile/%5B19%5D%20SirArchibald97)
> and not
> https://sky.shiiyu.moe/api/v2/profile/SirArchibald97

At first I thought this was the issue as well, however, the error message proves that the URL is formed correctly. I tried using Node-Fetch in a brand new project and it worked as expected, so I'm not really sure what the error is in my current project.

**Comment by SirArchibald97** [comment]
This is the code I am using:
```javascript
const fetch = require("node-fetch");
let res = await fetch(`https://sky.shiiyu.moe/api/v2/profile/${username}`);
let { profiles } = await res.json();
```
`username` is defined above and I have verfied that this isn't the issue as I have logged this value.

**Comment by SirArchibald97** [comment]
I have recreated my exact code in a new project and installed the same version of node-fetch however I only get the error in my first version. In the new project, the code works as expected.

**Comment by SirArchibald97** [comment]
So I have uninstalled node-fetch and am now using axios to fetch the data instead and it seems to be working fine now. I am still not sure why I was getting that error, but it's all good now!

**Comment by metalcupcake5** [comment]
Glad it's been resolved!
