### ISSUE TITLE
Broken features on specific profile

### ISSUE THREAD

**Issue by TeosDinok** [SkyCryptWebsite/SkyCrypt#2022]
**Describe the bug**
When trying to view my main profile on SkyCrypt, I'm welcomed with a strange URL (https://sky.shiiyu.moe/stats/0696189846e54593af0e0e23b78cd9d1/8dc90ad9-1fbb-43af-a07a-8255c7c7f32c) and many broken features, such as, but not limited to:

- Level progression, Skills progression and stats not showing up at the top of the page
- Skin on the left of the page is not there
- No info showing up when hovering or clicking on an item
- Unable to interact and open menus, such as inventories and missing accessories/pets
- Other informations not being displayed

**Profile/Location**
https://sky.shiiyu.moe/stats/Teos_Dinok/Mango

**Additional Info**
Any other profile work fine, and I was able to confirm that the issue is not local, as a friend of mine checked my SkyCrypt profile and witnessed the same results.
The profile seems to update whenever there is a change (such as switching pets, switching lobbies, having more or less coins in the bank/purse).

**Expected behavior**
I would expect to be able to view my main profile as I would any other working profile, mine and other players'.

**Screenshots**
I don't believe screenshots are necessary, since the issue doesn't seem to be only on my end.

**Desktop:**

- Windows 10
- Chrome
- Version 116.0.5845.141

**Comment by DuckySoLucky** [comment]
Hello, works fine for me so most likely you disabled JavaScript in your browser, if that doesn't help then can you send screenshot of console if there are any errors

**Comment by TeosDinok** [comment]
I never disabled JavaScript, but I did try to disable and re-enable it to see if it made any difference, but sadly no.

Here's the screenshot of the console errors
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/143914341/c9aa1166-d73b-4971-869d-c191139be88d)

What's really weird is, as I said, I don't have any issue on any other profile, nor player, it's only on that specific profile, although I did not try to look for someone with a Mango profile to see if that's what's causing the issue

**Comment by DuckySoLucky** [comment]
Thanks, gonna take a look at that tomorrow

**Comment by TeosDinok** [comment]
Hello, were you able to take another look at this issue?

**Comment by DuckySoLucky** [comment]
Heya. Sorry no something personal happened and I've been busy, gonna check it once I get free, sorry once again

**Comment by TeosDinok** [comment]
No worries, take all the time you need, was just wondering if you had any update or not. Hope nothing too serious happened, take care c:
