### ISSUE TITLE
The provided API doesn't work.

### ISSUE THREAD

**Issue by ashiqtasdid** [SkyCryptWebsite/SkyCrypt#2038]
**Describe the bug**
The provided API doesn't work. It throws a 502 error

**Expected behavior**
To give information about a profile.

**Screenshots**
[Image](https://i.ibb.co/93PLtPY/image.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Brave
- Version API v2.

**Additional context**
I want to use the API to create something for me. But, it's not working.

**Comment by DuckySoLucky** [comment]
Heya, thanks for information. Website is currently down, we're trying to get it back up as fast as possible, thanks for the patience

**Comment by ashiqtasdid** [comment]
Thank you very much. Please let me know as soon as you guys fix the issue
