### ISSUE TITLE
tippy tool tip shows up in the wrong spot

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#204]
**Describe the bug**
some of the tooltips are positioned incorrectly

**Profile/Location**
any

**Additional Info**
this bug also affects skylea

**Expected behavior**
tooltip points to the thing hovered over

**Screenshots**
![image](https://user-images.githubusercontent.com/44071655/103584827-147ed880-4eb0-11eb-9b80-4b131c769d9d.png)
![image](https://user-images.githubusercontent.com/44071655/103584826-134dab80-4eb0-11eb-99b9-e10222547c79.png)

**Browser:**
any

**Additional context**
this bug is caused by tippy trying to fit the tip within its parent that has overflow set

fixed by #161

**Comment by metalcupcake5** [comment]
Fixed with #161
