### ISSUE TITLE
The pack selection seems to not be working whatsoever

### ISSUE THREAD

**Issue by emifloofy** [SkyCryptWebsite/SkyCrypt#2050]
**Describe the bug**
I chose Vanilla, Worlds and Beyond and Hypixel Plus as my packs, but nothing had changed even after multiple refreshes. All the items were still mostly FurfSky with a couple items from Hypixel Plus.

**Expected behavior**
I expected that the textures would change to the ones from the selected packs.

**Screenshots**
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/53254254/207ba0c1-3f23-4794-9fb8-3972a3e9253b)
^ note that there's no "**RELOAD TO APPLY CHANGES**" button

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: Firefox
- Version: 118.0.1

**Smartphone (please complete the following information):**

Unneeded, as I couldn't find any option to change themes or packs on mobile anyways

**Attempted fixes**
Ctrl+Shift+R

**Comment by DuckySoLucky** [comment]
Fixed in #2048
