### ISSUE TITLE
selecting different packs does not work (can select but doenst change items)

### ISSUE THREAD

**Issue by jornboy** [SkyCryptWebsite/SkyCrypt#2051]
**Describe the bug**
changing packs does work in the menu but not on the items shown.

**Profile/Location**
(https://sky.shiiyu.moe/stats/Jornboy/Banana) but does it on all profiles

**Additional Info**
not in game but on the site.

**Expected behavior**
i clicked all packs of but still showed custom textures.

**Screenshots**
(https://youtu.be/KNscmrH7PiI)

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Browser [opera gx]
- Version [LVL 5 (core: 102.0.4880.90)]

**Additional context**
//

**Comment by DuckySoLucky** [comment]
Fixed in #2048, merged not in prod yet

@metalcupcake5 close this
