### ISSUE TITLE
Furfsky Reborn texture issue

### ISSUE THREAD

**Issue by mariethepolarfox** [SkyCryptWebsite/SkyCrypt#2082]
**Describe the bug**
Furfsky Reborn textures arent getting loaded, I dont know if this is a issue on their side or on your side, but im gonna try it here first.

**Profile/Location**
Every profile

**Expected behavior**

**Screenshots**
E.g.:
![Texture missing](https://github.com/SkyCryptWebsite/SkyCrypt/assets/80259183/cb549100-4127-44c6-991d-b13bdc80513a)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Opera GX

**Comment by DuckySoLucky** [comment]
Fixed in #2079
