### ISSUE TITLE
Unable to view own profile, says " Cannot read properties of undefined (reading 'none') "

### ISSUE THREAD

**Issue by 501st-Gamer** [SkyCryptWebsite/SkyCrypt#2085]
When i search for my own profile it says " Cannot read properties of undefined (reading 'none') ".

https://sky.shiiyu.moe/stats/the501stgamer

I expected to be able to view my profile as usual but unfortunately no, I can still view my friends profiles though.

I'm unable to link a screenshot currently.

- OS: Mac OS
- Chrome
- Unsure

**Comment by DuckySoLucky** [comment]
Fixedi n #2084

**Comment by metalcupcake5** [comment]
#2083
