### ISSUE TITLE
When trying to access my profile it says: Cannot read properties of undefined (reading 'none')

### ISSUE THREAD

**Issue by ArceusShiny000** [SkyCryptWebsite/SkyCrypt#2086]
My profile is this: https://sky.shiiyu.moe/stats/b1naryc0d3/Plancke
I was using an AOTD ,Strong Drag Armor and a Common Griffin.
OS: Win11
Browser: Opera GX

**Comment by DuckySoLucky** [comment]
Fixed in #2084

**Comment by metalcupcake5** [comment]
#2083

**Comment by ArceusShiny000** [comment]
How do i fix it then
