### ISSUE TITLE
bug in search waffi503

### ISSUE THREAD

**Issue by Waffi503** [SkyCryptWebsite/SkyCrypt#2087]
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/80223754/1b39b2b7-ed2c-4395-bf8c-5f01f521b746)
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/80223754/fe48b1a7-0367-4221-8f6e-9db897d8043c)

**Comment by abusingdeath** [comment]
I keep getting this same error on my profile @currentlyraining

**Comment by karakal12** [comment]
I have the same problem with fire__ferret

**Comment by DuckySoLucky** [comment]
@metalcupcake5

**Comment by metalcupcake5** [comment]
same as #2083, we are waiting for hypixel to fix
