### ISSUE TITLE
Error Cannot read properties of undefined (reading 'bronze')

### ISSUE THREAD

**Issue by Halhadus** [SkyCryptWebsite/SkyCrypt#2089]
**Describe the bug**
When I search my username, "Error
Cannot read properties of undefined (reading 'bronze')" error appearing.

**Profile/Location**
https://sky.shiiyu.moe/stats/Halhadus

**Screenshots**

![Screenshot_20231122-193951_Fennec](https://github.com/SkyCryptWebsite/SkyCrypt/assets/76776068/96a3dd12-b21e-4876-9611-f1245fc9d1a6)

**Smartphone (please complete the following information):**

- Device: Redmi Note 8 Pro (begonia)
- OS: Android 13
- Browser: Fennec Fdroid
- Version: 119.1.0

**Comment by DuckySoLucky** [comment]
@metalcupcake5 close this

**Comment by Halhadus** [comment]
> @metalcupcake5 close this

Why?

**Comment by Magnus1001** [comment]
Same

**Comment by metalcupcake5** [comment]
same as #2083, we are waiting for hypixel to fix
