### ISSUE TITLE
Error Cannot read properties of undefined (reading 'bronze')

### ISSUE THREAD

**Issue by Itsnotbar2** [SkyCryptWebsite/SkyCrypt#2090]
**Describe the bug**
When i search my profile its says the title and i can't access it and its happening with few other accounts like luffyzoro1 and cat3124

**Profile/Location**
Its just the main skycrypt link cuz its in the search box

**Additional Info**
Hmm no additional info

**Expected behavior**
I expect it to work just fine and show my account

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. samsung s21]
- Browser [e.g. chrome]
- Version [e.g. idk]

**Smartphone (please complete the following information):**

- Device: [e.g. samsung s21]
- OS: [e.g. i think its apk idk]
- Browser [e.g. chrome]
- Version [e.g. idk]

**Additional context**

**Comment by metalcupcake5** [comment]
same as #2083, we are waiting for hypixel to fix
