### ISSUE TITLE
Cannot read properties of undefined (reading 'dojo_points_sword_swap') when searching for profile

### ISSUE THREAD

**Issue by Labousci27** [SkyCryptWebsite/SkyCrypt#2091]
**Describe the bug**
When attempting to look up my username on the site I get a box that says
"Cannot read properties of undefined (reading 'dojo_points_sword_swap')"
**Profile/Location**
(https://sky.shiiyu.moe/stats/Labousci27)

**Screenshots**
![Screenshot 2023-11-23 005718](https://github.com/SkyCryptWebsite/SkyCrypt/assets/151814119/aaf03620-2890-41b8-8eff-e08f214e4288)
**Desktop (please complete the following information):**

- OS: Windows 10
- Chrome

**Comment by metalcupcake5** [comment]
same as #2083, we are waiting for hypixel to fix
