### ISSUE TITLE
Cannot read properties of undefined (reading 'none')

### ISSUE THREAD

**Issue by Erickeyz** [SkyCryptWebsite/SkyCrypt#2093]
**Describe the bug**
Cannot read properties of undefined (reading 'none')

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)

**Screenshots**

**Desktop (please complete the following information):**

Windows 10
![Screenshot 2023-11-23 220157](https://github.com/SkyCryptWebsite/SkyCrypt/assets/83922023/9228c82d-2fe6-4309-a36b-468192e5ce2a)

chrome,

**Comment by metalcupcake5** [comment]
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/43897385/8eeb39e3-e5c7-433b-b489-d83cd32f00d2)
