### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Neduskinas** [SkyCryptWebsite/SkyCrypt#2094]
**Describe the bug**
A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]

**Smartphone (please complete the following information):**

**Additional context**
When i try to search my account on sky.shiiyu.moe website, it say's that account is not found. Account name: Margutisss

**Comment by Zickles** [comment]
did you read the pinned issue #2092 
also why did you put the problem in additional context
