### ISSUE TITLE
Facing consistent error "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by HarshShah14** [SkyCryptWebsite/SkyCrypt#2097]
**Describe the bug**
My username is Green__Man, I used to be able to see my stats on the website a while back. I took a break from the game and started playing recently. it's been about 3 weeks now and I still cannot view my stats.
**Profile/Location**
https://sky.shiiyu.moe/stats/green__man

**Additional Info**
Livid Dagger, Necron Armour

**Expected behavior**
The website to open and show me my stats

**Screenshots**
<img width="1120" alt="Screenshot 2023-11-27 at 9 22 00 PM" src="https://github.com/SkyCryptWebsite/SkyCrypt/assets/147622172/59b15c6d-4bcd-4c74-9d13-8d013a5581e2">

**Desktop (please complete the following information):**

- OS: MAC OS
- Browser chrome and Safari (tried both)
- Version 10.15.7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by metalcupcake5** [comment]
holy moly please read #2092
