### ISSUE TITLE
Strange White Screen

### ISSUE THREAD

**Issue by GamingShadow64** [SkyCryptWebsite/SkyCrypt#2098]
Whenever I try to open my profile I am met with a pure white screen

https://sky.shiiyu.moe/stats/GamingShadow64

Normally you'd get actual information like every other profile is visited but for some reason, mine is the only one (that I've found) that refuses to show anything

![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/152237458/e6fc6c71-7f33-4094-89a5-b8b603b16757) 
This is what happens when you try to view my profile

- OS: Windows 10
- Browser Chrome 
- Version 119.0.6045.159

Id also like to say, unlike other issues I've seen reported. My profile doesn't say anything isn't detected it just doesn't show anything

**Comment by pandavilly333** [comment]
I'm having the same issue on my profile. pandavilly333. I haven't been able to view it for a week now.

**Comment by DuckySoLucky** [comment]
@metalcupcake5 close this

**Comment by DuckySoLucky** [comment]
fix: temporarily use https://cupcake.shiiyu.moe/
