### ISSUE TITLE
make slayer containers have good css

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#210]
**Is your suggestion related to a problem? Please describe in detail.**
slayer containers are a huge pile of `position: absolute` and they don't deal properly with long text

**Describe your suggestion**
redo it to use modern dynamic css

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/44071655/103709899-a571b480-4f81-11eb-8051-47ed56bb705d.png)

**Additional context**
This issue exists mostly as a todo for me but if someone else wants to fix it they can

**Comment by metalcupcake5** [comment]
I believe this was fixed in #211 or similar

**Comment by nstringham** [comment]
Slayer CSS is still pretty messy #211 was just fixing some symptoms not the underlying problem
