### ISSUE TITLE
White Screen on Skycript

### ISSUE THREAD

**Issue by citr0net** [SkyCryptWebsite/SkyCrypt#2114]
**Describe the bug**
When I search my username on Skycript I get prompted with a WhiteScreen

**Profile/Location**
(https://sky.shiiyu.moe/stats/CitrusIntellect)

**Additional Info**
Shadow Assasin, Livid Dagger, And i think Griffin pet (Epic) but my gear stats dont matter for this error

**Expected behavior**
I go to my profile

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser Any
- Version What the website is running

**Comment by DuckySoLucky** [comment]
@metalcupcake5
