### ISSUE TITLE
I can't see my profile on skylea

### ISSUE THREAD

**Issue by Leonheartop** [SkyCryptWebsite/SkyCrypt#2115]
When i try to search my name on skylea, my profile doesn't show up.

https://sky.shiiyu.moe/stats/LeonheartOP/Raspberry

- OS:  Windows 11
- Browser: chrome

- Device: Vivobook_asusLaptop
![Screenshot 2023-12-05 121624](https://github.com/SkyCryptWebsite/SkyCrypt/assets/152975282/d443ef2f-f9b7-418f-8243-5c99ff552949)

**Comment by citr0net** [comment]
I am having this same exact problem (CitrusIntellect)

**Comment by DuckySoLucky** [comment]
@metalcupcake5
