### ISSUE TITLE
I can't see my profile on SkyCrypt

### ISSUE THREAD

**Issue by BadGamer420** [SkyCryptWebsite/SkyCrypt#2116]
**Describe the bug**
A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DuckySoLucky** [comment]
@metalcupcake5
