### ISSUE TITLE
scroll bar on invintory tabs

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#213]
**Describe the bug**
there is a verticle scroll bar on the inventory tabs

**Profile/Location**
any

**Additional Info**
only effects viewports wider than 1200px

**Expected behavior**
no verticle scroll bar

**Screenshots**
![image](https://user-images.githubusercontent.com/44071655/103739482-ae837580-4fc3-11eb-85d1-6645f6daf1e1.png)

**Browsers:**
- Windows Chrome 87
- Windows Firefox 84

**Additional context**
- bug originally reported on discord by @FantasmicGalaxy 
- possibly related to #212

**Comment by RicardormDev** [comment]
I'll fix this.
