### ISSUE TITLE
Coins API failure

### ISSUE THREAD

**Issue by FallBackITA27** [SkyCryptWebsite/SkyCrypt#2153]
Coins API returns `{"error":"allProfiles.filter is not a function or its return value is not iterable"}`

**Profile/Location**
Any profile I've tried so far
https://sky.shiiyu.moe/api/v2/coins/FallBackITA27/Grapes/
https://sky.shiiyu.moe/api/v2/coins/eadwod/Orange/
https://sky.shiiyu.moe/api/v2/coins/gyarumom/Mango
https://sky.shiiyu.moe/api/v2/coins/LesbianCatgirl/Lemon/

**Additional context**
The issue seems to trace back to [here](https://github.com/SkyCryptWebsite/SkyCrypt/blob/development/src/lib.js#L136C28-L136C28).

**Comment by DuckySoLucky** [comment]
expect a fix within the next 2-3 business days
