### ISSUE TITLE
ERROR  Cannot convert a BigInt value to a number 

### ISSUE THREAD

**Issue by drmrti** [SkyCryptWebsite/SkyCrypt#2157]
**Describe the bug**
When entering a few usernames such as the ones listed in this report (this doesnt happen with all usernames) the following error occurs: ERROR  Cannot convert a BigInt value to a number

**Profile/Location**
https://sky.shiiyu.moe/stats/dreadingg  https://sky.shiiyu.moe/stats/Dario_on_IOS__2

**Additional Info**
N/A

**Expected behavior**
id usually expect the site to show me the accounts stats (ive searched the names listed in the post in the past with no trouble)

**Screenshots**
![2024-01-08 23_01_17-Greenshot](https://github.com/SkyCryptWebsite/SkyCrypt/assets/156026488/9882fba6-7fc1-440c-9101-ebe78cf51811)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version idk

**Additional context**
This error doent show anything (stats) at all, it isnt some error with profiles or anything. It doesnt even let you access them, you are stuck in the search bar from when you first open the website.

**Comment by ghost** [comment]
Ive got the same issue for "Banishedddd"

**Comment by metalcupcake5** [comment]
Fixed in #2156
