### ISSUE TITLE
Wrong CSS class in Bestiary

### ISSUE THREAD

**Issue by mrdeadi02** [SkyCryptWebsite/SkyCrypt#2164]
**Describe the bug**
My silverfish bestiary should not have a max-stat CSS class, because it only 5573/10000

**Profile/Location**
(https://sky.shiiyu.moe/stats/mrdd02/Banana#Bestiary) (Silverfish)

**Additional Info**
-

**Expected behaviour**
The container does not have a max-stat CSS class.

**Screenshots**
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/42602656/88fff8d9-f2a2-468f-882e-207d9eff09dd)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 120.0.6099.217

**Additional context**
-

**Comment by DuckySoLucky** [comment]
oops, must've accidentally missed that, ty for info. expect fix within 2-3 business days

**Comment by mrdeadi02** [comment]
@DuckySoLucky Same problem with Fels:
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/42602656/717922d1-7d56-4e79-8f2b-b7612fe304c0)

**Comment by DuckySoLucky** [comment]
Thanks. I'm busy til the Friday so cannot really fix it at this moment sorry. most likely in like week and half or so

**Comment by Zickles** [comment]
found the problem for some reason the max tier is zero and i have no idea why. and its only for Fels and Silverfish

**Comment by DuckySoLucky** [comment]
> @DuckySoLucky Same problem with Fels: ![image](https://private-user-images.githubusercontent.com/42602656/296449600-717922d1-7d56-4e79-8f2b-b7612fe304c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3ODA3NjIsIm5iZiI6MTcwNTc4MDQ2MiwicGF0aCI6Ii80MjYwMjY1Ni8yOTY0NDk2MDAtNzE3OTIyZDEtN2Q1Ni00ZTc5LThmMmItYjc2MTJmZTMwNGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE5NTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiODYxMDIwMDk0OTM1ZmEyMDc0Njg5M2NlZWYyNTgxODVmYmRiZWQ4NzEyYWE5NjA5NzUzMjFmMDdjOTg0NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9PQuPG-IVdBNAeWWf9ejTFnJV_n-a9vkGDm7LgoJU-Q)

Should be fixed in #2172, sorry for taking longer than usual I was quite busy irl
