### ISSUE TITLE
api retrieving issue when the player haven't used the site search

### ISSUE THREAD

**Issue by AnsonYeung** [SkyCryptWebsite/SkyCrypt#22]
**Describe the bug**
When a player doesn't use the search box in the main page and directly opened the API instead, it will show that player don't have any skyblock profiles.

**Profile/Location**
This is replicable with an account that haven't used the search function yet and with any API (e.g. profiles, talismans). Try it with your guild members yourself and I won't post any usernames here.

**Expected behavior**
API being fetched and correct API result being returned.

**Smartphone (please complete the following information):**
 - Device: -
 - OS: Android 10
 - Browser Google Chrome
 - Version 85.0.4183.81

**Comment by metalcupcake5** [comment]
Expected behavior, as it only searches for cached data so the site doesn't get overloaded.

**Comment by AnsonYeung** [comment]
This doesn't happen with every profile. But I can show you some if you want. However, I don't want to post their usernames here so that this bug still exist.

**Comment by Shiiyu** [comment]
As cupcake specified, the API currently pulls from the cache. This is the same behavior as the API on https://sky.lea.moe/ We may have the API send requests to hypixel in the future, but for now it isn't a viable option as we do not have a big enough key to support the requests. If the profile has never been searched before it will not appear in our API.
