### ISSUE TITLE
Redirects to an old account when I type in my user

### ISSUE THREAD

**Issue by noodleswut** [SkyCryptWebsite/SkyCrypt#2216]
My old account Noodleswut was hacked a few months ago and I’ve made a new one. The old one is now noodleswut1 I guess now? At least on Skycrypt. However, when I enter Noodleswut into the search it shows my old account. 

When I /pv (idk what mod this is for) it shows my current account but when I click on the redirect to skycrypt it just shows my old account as well. 

The old account is no longer active since Microsoft closed the account

https://sky.shiiyu.moe/stats/noodleswut1/Strawberry

**Comment by Mpro256** [comment]
Hey!

I just thought I would say that this has happened to my friends account before. It was resolved after he just waited a bit. I know it doesn't help that much but yeah.

Thanks!

**Comment by DespicableGoose** [comment]
Seems fine to me now, can probably be closed.

**Comment by DuckySoLucky** [comment]
> Seems fine to me now, can probably be closed.

yeah we switched to another API. @metalcupcake5
