### ISSUE TITLE
Dragons killed in less than 1 second are shown without the "0." in front.

### ISSUE THREAD

**Issue by Rubyrak** [SkyCryptWebsite/SkyCrypt#2250]
**Describe the bug**
In Misc, Dragons section, if you have helped killing a dragon and it died in less than 1 second, it is shown without the "0." front, so if you have a dragon killed in 0.950 seconds, as in my case, it will show as if it were 950 seconds.

**Profile/Location**
[Rubyrak on Watermelon](https://sky.shiiyu.moe/stats/Rubyrak/Watermelon#Misc)

**Expected behavior**
Show, at least in this case, 0.950s instead of 950s

**Screenshots**
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/94675541/70c4633e-7b3d-4680-a601-27da0d8e8792)
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/94675541/8daeaab8-b32a-47a7-b7aa-ac265a082e35)
I know that the second image does not show the decimals, but it looks like it takes less than 1 second.

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Browser [Google Chrome]
- Version [124]

**Comment by DuckySoLucky** [comment]
Ty for report, expect fix within the next 2-3 business days (I'm busy t like June, idk about other developers)
