### ISSUE TITLE
HotM Tree shows wrong

### ISSUE THREAD

**Issue by XiaoHeiawa** [SkyCryptWebsite/SkyCrypt#2273]
New HotM tree updated, but there are lots of perks shows wrong on website.

Profile: https://sky.shiiyu.moe/stats/XiaoHei_awa/Banana#Skills

**Comment by DuckySoLucky** [comment]
Yeah because it's hard coded, crap ton of work is needed, usually I would update it. But I'm quite busy this month so i don't believe that it's gonna get updated any time soon
