### ISSUE TITLE
Small description error in ice essence shop

### ISSUE THREAD

**Issue by DocMatey** [SkyCryptWebsite/SkyCrypt#2294]
The frozen skin perk in the ice essence shop under miscellaneous has the wrong description it being:
     - "Increases your Defense by 2-10 while on Jerry's Workshop"
 Whereas it should say:
      - "Grants 2-10❄Cold Resistance"

I'm not personally bothered by this; I just wanted to give a heads-up so it won't confuse anyone looking at it.

**Comment by nphcrafter** [comment]
Changed it, waiting for review
