### ISSUE TITLE
Repeat Talismans should be part of NW

### ISSUE THREAD

**Issue by Deep3681** [SkyCryptWebsite/SkyCrypt#2299]
**Is your suggestion related to a problem? Please describe in detail.**
A clear and concise description of what the problem is.
Ex. [...] doesn't work, [...] solves it.

**Describe your suggestion**
Repeat talismans shouldn't be counted as part of your network since you can just buy a bunch of say great spook artifacts to inflate your net worth artificially.
**Describe alternatives you've considered**
Ex. [...] could be a problem, but [...]
Only count 1 version of each talisman towards net worth.
**Additional context**
Add any other context or screenshots about the suggestion here.

**Comment by DuckySoLucky** [comment]
Heya, developer of SkyHelper here (owners of the Networth calculation, prices etc..), so yeah no. we will not implement that, it makes no sense that's like saying if player has 2 Hyperions only one should be accounted in the nw calc
