### ISSUE TITLE
Possible issue with username

### ISSUE THREAD

**Issue by AnsonYeung** [SkyCryptWebsite/SkyCrypt#23]
**Describe the bug**
When a player username contains a underscore(I guess, I can give you the username for you to look into), the API will return `{"error":"TypeError: Cannot read property 'includes' of undefined"}`
However, the main page still shows the player data properly.

**Comment by WarpWing** [comment]
I would like the username :D

**Comment by AnsonYeung** [comment]
[Random Guy on Forum](https://sky.shiiyu.moe/api/v2/profile/ankles_)

**Comment by WarpWing** [comment]
Mostly likely, it's is _ throwing us a error. Will look into though it probably won't be me. I need to look into other stuff. Mostly like it would be @boblovespi  or @metalcupcake5

**Comment by WarpWing** [comment]
Looking over it now, it does seem like it's calling a method on a object that doesn't exist. Probably resolving something different that what's it's supposed to but that's just me <3

**Comment by WarpWing** [comment]
API is currently on lockdown. I am closing this issue but it will be open in the future when API is back up

**Comment by metalcupcake5** [comment]
API is back up, I'll try to look at this soon.

**Comment by WarpWing** [comment]
@metalcupcake5  did you ever find a fix for this?
