### ISSUE TITLE
Error when starting site

### ISSUE THREAD

**Issue by Nim1com** [SkyCryptWebsite/SkyCrypt#235]
**Describe the bug**
Site not starting up.

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
No errors

**Screenshots**
> SkyCrypt@1.0.0 start C:\Users\nikla\Desktop\GITHUB\SkyCrypt
> node init && node index

(node:175732) UnhandledPromiseRejectionWarning: Error: The module '\\?\C:\Users\nikla\Desktop\GITHUB\SkyCrypt\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\nikla\Desktop\GITHUB\SkyCrypt\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:175732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:175732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:175732) UnhandledPromiseRejectionWarning: MongoServerSelectionError: connection <monitor> to 34.70.100.184:27017 closed
    at Timeout._onTimeout (C:\Users\nikla\Desktop\GITHUB\SkyCrypt\node_modules\mongodb\lib\core\sdam\topology.js:438:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:175732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: NO

**Additional context**
I have node version 14

**Comment by Nim1com** [comment]
re installind stuff dosnt work

**Comment by metalcupcake5** [comment]
The solution is very clearly listed in the error message.

**Comment by metalcupcake5** [comment]
Try removing the `node_modules` folder and re-installing.

**Comment by Nim1com** [comment]
(node:195740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:195740) UnhandledPromiseRejectionWarning: MongoServerSelectionError: connection <monitor> to 34.70.100.184:27017 closed
    at Timeout._onTimeout (C:\Users\nikla\Desktop\GITHUB\SkyCrypt\node_modules\mongodb\lib\core\sdam\topology.js:438:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:195740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandle

**Comment by Nim1com** [comment]
somthing with mongo not working

**Comment by Nim1com** [comment]
dont know what

**Comment by metalcupcake5** [comment]
Hid the comment because of an ip adress. It looks like you have an incorrect mongo db adress.

**Comment by Nim1com** [comment]
no im hosting mongo on atlas

**Comment by metalcupcake5** [comment]
What are you entering for the connection address?

**Comment by metalcupcake5** [comment]
Changed the title to better reflect the error, hope that's OK.

**Comment by Nim1com** [comment]
The Problem was mongo thanks for the help!
