### ISSUE TITLE
Epic rarity Mithril Golem shows the 3rd perk

### ISSUE THREAD

**Issue by AnthonyFic-code** [SkyCryptWebsite/SkyCrypt#239]
**Describe the bug**
Mithril Golem’s 3rd ability shows on the epic rarity

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Antd17/Coconut
**Additional Info**
My level 72 mithril golem pet

**Expected behavior**
It shouldn’t be there since the 3rd perk is only on legendary

**Screenshots**
![0F74B229-ECAA-4206-8482-D614D1857DE0](https://user-images.githubusercontent.com/76977714/104885452-15931980-5936-11eb-8ed8-ebcc4cf524e8.jpeg)

**Smartphone:**
 - Device: iPhone 8
 - OS: 14.0
 - Browser: Safari
 - Version: current

**Comment by metalcupcake5** [comment]
already fixed

**Comment by metalcupcake5** [comment]
oops sorry it wasn't on prod, i'll pull and restart the site now

**Comment by metalcupcake5** [comment]
alright it should be live

**Comment by metalcupcake5** [comment]
![image](https://user-images.githubusercontent.com/43897385/104886078-f9837e00-591d-11eb-89b9-56496d587666.png)

**Comment by AnthonyFic-code** [comment]
can confirm
