### ISSUE TITLE
Support for Fuckit.js 

### ISSUE THREAD

**Issue by WarpWing** [SkyCryptWebsite/SkyCrypt#244]
**Describe your suggestion**
This is a suggestion to implement [FuckIt.js ](https://github.com/mattdiamond/fuckitjs) to allow code to always run. Great for debugging and production-ready! FuckItJS uses state-of-the-art technology to make sure your javascript code runs whether the compiler likes it or not.

**Comment by Shiiyu** [comment]
As much as I love this idea, for the sake of everything not having negative consequences, is a definite no.

**Comment by WarpWing** [comment]
> As much as I love this idea, for the sake of everything not having negative consequences, is a definite no.

Awwwww but funni :(
