### ISSUE TITLE
Slayer XP bugged

### ISSUE THREAD

**Issue by Brandonion** [SkyCryptWebsite/SkyCrypt#245]
**Describe the bug**
The Slayer XP is not correct

**Profile/Location**
https://sky.shiiyu.moe/stats/Breadstonks/Papaya 

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
On the website, it says that I am tarantula level four and am 1k xp over level 4, but ingame, it says that I am 5 xp over level 4

**Desktop (please complete the following information):**
Windows 10, Google Chrome, not sure what version

**Smartphone (please complete the following information):**
LG G7 thinq, google chrome, not sure what version

**Comment by metalcupcake5** [comment]
Can you post a screenshot of your xp to the next level?

**Comment by Brandonion** [comment]
![image](https://user-images.githubusercontent.com/72035838/105447099-66ea2400-5c28-11eb-9af6-5af4f09ef439.png)
I dont have a picture of the stats ingame, but I just achieved tarantula level four a few days ago

**Comment by metalcupcake5** [comment]
Sorry, i meant an in-game screenshot

**Comment by metalcupcake5** [comment]
Also the website looks like it says 30 xp over level 4

**Comment by Brandonion** [comment]
Oh, I don't have one ingame, and I cannot go online at the moment, but the
website says I'm 1030k over level 4

**Comment by Brandonion** [comment]
I don't have a picture ingame, sorry

**Comment by Brandonion** [comment]
Also, when I was 500 xp away from level 4, the website stated that I have unclaimed slayer level rewards, but I don't actually have any unclaimed rewards

**Comment by metalcupcake5** [comment]
I don't have much to go on currently, both the API and the website state that you have 30 xp over level 4.
If you can get a screenshot that would be great 😄

**Comment by Brandonion** [comment]
I will try :)

**Comment by Brandonion** [comment]
I'll probably go online sometime next week or earlier, is that okay with you?

**Comment by Brandonion** [comment]
I am so sorry! I was thinking, the day before I was level 4, I have 470xp remaining, so I did 5 more tier threes, so then that would add up to 30xp above level 4, so the website is right. I am sorry if this caused you any trouble :(

**Comment by metalcupcake5** [comment]
Its fine, glad its correct!
