### ISSUE TITLE
*not sure if this is bug or suggestion* but armor with the rarity of supreme has no background color

### ISSUE THREAD

**Issue by h8re** [SkyCryptWebsite/SkyCrypt#247]
![Screenshot_2021-01-22-20-13-28-923_com android chrome~2](https://user-images.githubusercontent.com/70304266/105564071-9499a080-5cee-11eb-8a7d-6f17693251ec.jpg)
![Screenshot_2021-01-22-20-13-25-115_com android chrome~2](https://user-images.githubusercontent.com/70304266/105564126-c9a5f300-5cee-11eb-9981-fa496e66eeb1.jpg)

above I've provided screenshots to example peices, and how they lack any red background color (which would represent their rarity) chestplate is NOT supreme rarity don't pay attention to it

https://sky.shiiyu.moe/stats/h8re/Blueberry

**Comment by nstringham** [comment]
a quick look at [index.css lines 2006-2088](https://github.com/SkyCryptWebsite/SkyCrypt/blob/master/public/resources/css/index.css#L2006-L2088) reveals that there is not color for supreme in skycrypt if someone tells me a color to use I would gladly implement it

**Comment by dukio** [comment]
So there's the official minecraft color (AA0000) and the color used by the lore renderer (CC3333), found here:
![image](https://user-images.githubusercontent.com/2744227/105618993-466bc680-5dee-11eb-94f0-6cbdfb6b8e1c.png)


---
**Minecraft**
![image](https://user-images.githubusercontent.com/2744227/105619004-584d6980-5dee-11eb-9cf6-8efedb2dcbb9.png)


---
**Lore renderer**
![image](https://user-images.githubusercontent.com/2744227/105618974-22a88080-5dee-11eb-943f-8f216e0d9d49.png)

---
I would also compare it to the current color of the SPECIAL tier, to try and not make similar colors:
![image](https://user-images.githubusercontent.com/2744227/105619023-859a1780-5dee-11eb-97e6-3f028fe6200b.png)
![image](https://user-images.githubusercontent.com/2744227/105619030-a6fb0380-5dee-11eb-9fdd-2adc8f44c516.png)


Personally I don't mind either; the minecraft original color is.... well.... the original and most correct one to use. On the other hand I would like to know why Lea (or who coded the base lore renderer) decided to use a different color than the vanilla one for §4 | dark_red

**Comment by nstringham** [comment]
Many of the colors on SkyCrypt are intentionally incorrect because they look better This is unlikely to change in the near future but I do have plans to eventually allow you to choose whether you'd like to use the more aesthetic colors or the more accurate colors

**Comment by nstringham** [comment]
I would recommend changing the labels on this issue from bug to feature request

**Comment by h8re** [comment]
> So there's the official minecraft color (AA0000) and the color used by the lore renderer (CC3333), found here:
> ![image](https://user-images.githubusercontent.com/2744227/105618993-466bc680-5dee-11eb-94f0-6cbdfb6b8e1c.png)
> 
> **Minecraft**
> ![image](https://user-images.githubusercontent.com/2744227/105619004-584d6980-5dee-11eb-9cf6-8efedb2dcbb9.png)
> 
> **Lore renderer**
> ![image](https://user-images.githubusercontent.com/2744227/105618974-22a88080-5dee-11eb-943f-8f216e0d9d49.png)
> 
> I would also compare it to the current color of the SPECIAL tier, to try and not make similar colors:
> ![image](https://user-images.githubusercontent.com/2744227/105619023-859a1780-5dee-11eb-97e6-3f028fe6200b.png)
> ![image](https://user-images.githubusercontent.com/2744227/105619030-a6fb0380-5dee-11eb-9fdd-2adc8f44c516.png)
> 
> Personally I don't mind either; the minecraft original color is.... well.... the original and most correct one to use. On the other hand I would like to know why Lea (or who coded the base lore renderer) decided to use a different color than the vanilla one for §4 | dark_red

this was going to be what I suggested but I couldn't get back to my computer to get the hexadecimal thanks mate

**Comment by nstringham** [comment]
It looks like we all kind of forgot about this issue but it's definitely still a problem I'm currently working on an overhaul to the color system and I'll make sure to include supreme

**Comment by nstringham** [comment]
I'm going with #920909 for now
![image](https://user-images.githubusercontent.com/44071655/112681185-b7f2e000-8e44-11eb-85d4-b54046fba44e.png)
