### ISSUE TITLE
Texture pack not loading

### ISSUE THREAD

**Issue by Artinator11** [SkyCryptWebsite/SkyCrypt#256]
**Describe the bug**
I Have Adaptive Chestplate, leggings and boots but only the texture of the leggings are showing. I think its because my Chestplate and boots are fragged, but my leggings are not.
I'm using the Hypixel Skyblock pack v13.

**Profile/Location**
https://sky.shiiyu.moe/stats/Artinator11/Papaya

**Expected behaviour**
I Expected for the texture of my armour to load correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/71243393/106353279-80ccea80-633d-11eb-9ebd-ae769c88658a.png)
![image](https://user-images.githubusercontent.com/71243393/106353284-8d514300-633d-11eb-9e19-3fa53d90441b.png)
![image](https://user-images.githubusercontent.com/71243393/106353291-96421480-633d-11eb-8a43-145da5a44224.png)
![image](https://user-images.githubusercontent.com/71243393/106353293-9a6e3200-633d-11eb-98c4-140082429e7c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 10

**Comment by metalcupcake5** [comment]
Do the textures appear in-game?

**Comment by Artinator11** [comment]
Yes the textures do appear in game

**Comment by nstringham** [comment]
Is this still broken or has it bean fixed? [Artinator11/Papaya](https://sky.shiiyu.moe/stats/Artinator11/Papaya) seams not to have this armor anymore can someone link to a profile that does

**Comment by metalcupcake5** [comment]
Pretty sure its still happening, once I had a chance to test it the profile didn't have the armor already

**Comment by Artinator11** [comment]
It's still happening
The leggings and bonzo staff for this profile aren't loading
https://sky.shiiyu.moe/stats/lv_oz2/Mango
![image](https://user-images.githubusercontent.com/71243393/112695200-c6d6a280-8ed7-11eb-835f-e28e4d100c19.png)
![image](https://user-images.githubusercontent.com/71243393/112695217-cdfdb080-8ed7-11eb-9059-1ebbbf86fc10.png)

**Comment by nstringham** [comment]
Are any packs other than Hypixel Skyblock pack v13 effected?

**Comment by Artinator11** [comment]
Well only the Hypixel Skyblock pack v13 has a texture for Adaptive armour
But the bonzo staff on the profile loads the texture when using Furfsky reborn

**Comment by nstringham** [comment]
can confirm still a problem
![image](https://user-images.githubusercontent.com/44071655/121809097-7f83c680-cc29-11eb-9ffa-c9ecd8342d15.png)

tested with https://sky.shiiyu.moe/stats/lv_oz2/Mango#Inventory
