### ISSUE TITLE
Full Accessory Bag not Showing

### ISSUE THREAD

**Issue by Artinator11** [SkyCryptWebsite/SkyCrypt#257]
Describe the bug
If you click on inventory then go into the Accessories tab, it only shows the slots that have been unlocked via Redstone collection. Any slots that have been unlocked through the community centre upgrade won't appear in the accessory bag tab under inventory though the Accessories will still register.
I'm Currently missing either 6 or 4 slots.

Profile/Location
https://sky.shiiyu.moe/stats/Artinator11/Papaya

Expected behaviour
I expected all my unlocked Accessory bag slots to appear in correct number

Screenshots
![image](https://user-images.githubusercontent.com/71243393/106353731-c8a14100-6340-11eb-9049-574b323744df.png)

Desktop

OS: Windows
Browser: Chrome
Version: 10

**Comment by nstringham** [comment]
fixed by ede5a6987a1b8d8120775a9b78e0dbbcc7f1e1ad

**Comment by nstringham** [comment]
This is because the hard-coded bag sizes don't take upgrades from the town hall into consideration My solution is to just stop using hard-coded values because the API appears to be accurate I'll make a PR to fix this as soon as #250 is merged

**Comment by nstringham** [comment]
@Artinator11 is this the correct number of slots for your Papaya profile?
![image](https://user-images.githubusercontent.com/44071655/106367205-e8b80c80-630e-11eb-98cc-2b8ec5185706.png)
