### ISSUE TITLE
Bank amount

### ISSUE THREAD

**Issue by Artinator11** [SkyCryptWebsite/SkyCrypt#261]
**Describe the bug**
At the top the the profile below the stats, the bank amount is always on zero. I have my Bank API on, and a couple of my other friends do too, but the bank balance for my profile and their profiles' always remain at zero. 

**Profile/Location**
https://sky.shiiyu.moe/stats/Artinator11/Papaya

**Expected behaviour**
I expected for the bank balance to return with the correct number.

**Screenshots**
![image](https://user-images.githubusercontent.com/71243393/106878989-b5bab200-672e-11eb-99e2-074d2836eae1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Artinator11** [comment]
Third issue this week

**Comment by metalcupcake5** [comment]
I don't think we can do anything about this, the hypixel api says you have exactly `0.034321938233915716` coins
![image](https://user-images.githubusercontent.com/43897385/106928103-b10ee300-66c7-11eb-87f5-63cb5c424f3a.png)

**Comment by metalcupcake5** [comment]
Its an error on hypixel's side
