### ISSUE TITLE
Inventory isn't properly rendered

### ISSUE THREAD

**Issue by symt** [SkyCryptWebsite/SkyCrypt#267]
<img width="927" alt="Screen Shot 2021-02-05 at 6 16 02 PM" src="https://user-images.githubusercontent.com/28537235/107101846-3c7a9800-67de-11eb-87f3-84f396453f45.png">
Account in question: https://sky.shiiyu.moe/stats/meyi/Grapes

I'm running Firefox Nightly build 87.0a1 (2021-02-04) on macOS Big Sur 11.0.1 (20B50)

I don't know how else to describe it. There aren't any related errors in console. I checked the inventory's styles in both Firefox and Chrome and they matched.

Attached below are the computed styles for the inventory-slot element on both Chrome and Firefox.

<img width="383" alt="Screen Shot 2021-02-05 at 6 38 09 PM" src="https://user-images.githubusercontent.com/28537235/107102874-64b7c600-67e1-11eb-83b8-89d8f37e0d3d.png">
<img width="553" alt="Screen Shot 2021-02-05 at 6 38 18 PM" src="https://user-images.githubusercontent.com/28537235/107102881-684b4d00-67e1-11eb-8e8b-57b8b2f82908.png">

*`display: block` is missing but it is active (Browser Styles)*

All of the different inventories, including backpacks, are broken. Below is the ender chest (full 9 pages): 
<img width="801" alt="Screen Shot 2021-02-05 at 6 48 28 PM" src="https://user-images.githubusercontent.com/28537235/107103293-ccbadc00-67e2-11eb-8fa4-ef3e176e58f7.png">

**Comment by symt** [comment]
If I had to take a guess, it's related to #265

**Comment by nstringham** [comment]
I'll look into this later tonight

**Comment by nstringham** [comment]
this bug occurs in nightly but everything is fine in stable.

this bug can be recreated in stable by setting `layout.css.aspect-ratio.enabled` to true

**Comment by nstringham** [comment]
this is caused by: https://bugzilla.mozilla.org/show_bug.cgi?id=1690422

**Comment by nstringham** [comment]
### My Conclusion:

This bug is caused by a bug in firefox. There are workarounds we could use but because it's fine in stable and firefox nightly is not a supported browser I would recommend the SkyCrypt team to do nothing unless/until Mozilla expresses intent to enable `layout.css.aspect-ratio.enabled` by default in Stable. My guess is that Mozilla will fix this bug before they ship.

in the meantime, I would recommend one of the following options to SkyCrypt users who use Firefox Nightly:
- Set `layout.css.aspect-ratio.enabled` to false in `about:config`
- Use Firefox Stable
- Just deal with it. The rest of the site still works
- Use sky.lea.moe

**Comment by symt** [comment]
> 
> ### My Conclusion:
> 
> This bug is caused by a bug in firefox. There are workarounds we could use but because it's fine in stable and firefox nightly is not a supported browser I would recommend the SkyCrypt team to do nothing unless/until Mozilla expresses intent to enable `layout.css.aspect-ratio.enabled` by default in Stable. My guess is that Mozilla will fix this bug before they ship.
> 
> in the meantime, I would recommend one of the following options to SkyCrypt users who use Firefox Nightly:
> 
>     * Set `layout.css.aspect-ratio.enabled` to false in `about:config`
> 
>     * Use Firefox Stable
> 
>     * Just deal with it. The rest of the site still works
> 
>     * Use sky.lea.moe

Ha, I should've known better.

I highly doubt more than a few people are using Nightly. Anyways, thank you. The first fix worked like a charm.

**Comment by metalcupcake5** [comment]
Thanks nate :D

**Comment by nstringham** [comment]
Mesa3D on discord reported that this bug effects stable. This appears to be an isolated incident for now.
