### ISSUE TITLE
Some enchantments like "Blast Protection" aren't fully colored

### ISSUE THREAD

**Issue by Untitled** [SkyCryptWebsite/SkyCrypt#28]
**EDIT**
There is also some OP special enchantments such as Growth L, would we add them to special enchantments list or don't consider these OP enchants? 

**Describe the bug**
Some enchantments, such as "Blast Protection VI" , which should be colored gold aren't colored completely.

**Profile/Location**
https://sky.shiiyu.moe/stats/Minikloon/Banana

**Expected behavior**
Fully Colored

**Screenshots**
![image](https://user-images.githubusercontent.com/33189830/91719282-894da900-eb84-11ea-8d4b-171ec15be8e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

#29

**Comment by WarpWing** [comment]
I would say they are special enchantments so we would add them in :D
