### ISSUE TITLE
Cannot load 56ms

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#299]
**Describe the bug**
Attempting to retrieve the profile for `56ms` hangs

**Profile/Location**
https://sky.shiiyu.moe/stats/56ms

**Additional Info**
Bug originally reported by @EtherealCrystal#3546 on discord

**Expected behavior**
The site will either load the profile or give an error message

**Browser:**
 - OS: Android 10
 - Browser: Chrome
 - Version: 88

**Additional Context**
This bug does not seem to affect sky lea https://sky.lea.moe/stats/56ms

**Comment by Untitled** [comment]
It works well when I tested.
Maybe too much information to deal with

**Comment by nstringham** [comment]
Upon further inspection the page does load but extremely slowly

**Comment by dukio** [comment]
He just has too much stuff to calculate in his enderchest.... maxed enderchest full of backpacks full of items....

**Comment by nstringham** [comment]
this has been basically resolved by the recent hardware upgrade
