### ISSUE TITLE
Not Accurate Stats

### ISSUE THREAD

**Issue by BillyScranner1** [SkyCryptWebsite/SkyCrypt#31]
**Describe the bug**
My hp is 1510, Speed 173%, Crit Damage 440%, Strength 413 and so on.
It says Hp 1,499, Speed 169%, Crit Damage 435%, Strength 402 and so on
.
**Profile/Location**
https://sky.lea.moe/stats/BillyScranner/Papaya

**Expected behavior**
Should be 100% accurate

**Screenshots**
![2020-08-31_14 58 53](https://user-images.githubusercontent.com/70547442/91772950-b016da00-eb9a-11ea-8db3-f1d01e7168e4.png)
![118405646_3723191801033858_6301912827441346766_n](https://user-images.githubusercontent.com/70547442/91773355-798d8f00-eb9b-11ea-9b5e-1c6db3dc8696.jpg)
**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 1.8.9

**Comment by boblovespi** [comment]
have you bought stats from the essence shop?

**Comment by metalcupcake5** [comment]
Also thats on skylea, it may be different on our website.

**Comment by boblovespi** [comment]
@metalcupcake5 its not

**Comment by BradyAtkinson** [comment]
Gravity talisman @metalcupcake5 you can close this.

**Comment by WarpWing** [comment]
Wait what do you mean Gravity Talis?

**Comment by metalcupcake5** [comment]
gravity talis gives strength and defense, but not health

**Comment by metalcupcake5** [comment]
health, speed, and cd are different

**Comment by BillyScranner1** [comment]
I have bought stats but this is before i bought it

**Comment by BillyScranner1** [comment]
and it's tier 1 bought stats so like 1-2

**Comment by BillyScranner1** [comment]
it doesn't count pet stats (That add to yours), And Catacombs level (it gives 1hp per level), The Annoying Harp Game Stats +intelligence, and possibly a few fairy souls it won't count, and idk the rest

**Comment by apollyon600** [comment]
Everything should be accounted for BUT THE Catacombs level, since hypixel doesn't provide a value for it.
Only way to determine a catacombs level is holding a dungeon gear in your inventory that calculates it.
Then a function that determines how much health is added.

Not to mention that hypixel api takes time to update.
Dungeon stats is also hard to track iirc, until hypixel brings out a value for this you are stuck with those stats.
But that doesn't really a difference.. right...? RIGHT..?

**Comment by BillyScranner1** [comment]
(btw i know it doesn't track pet cause my Crit Chance is 100% while my pet gives the other 7% and armor alone give 93%)

**Comment by apollyon600** [comment]
I will look at the code and see if I can create a pull request.

**Comment by boblovespi** [comment]
you know, its not like the devs arent aware of this issue

**Comment by boblovespi** [comment]
@BillyScranner1 what pet were you using when you took the screenshot of your stats in game?

**Comment by BillyScranner1** [comment]
Skeleton

**Comment by BillyScranner1** [comment]
Legendary level 64 Skeleton (normal)

**Comment by WarpWing** [comment]
Congrats :D This issue is a week old

**Comment by boblovespi** [comment]
warp that was unnecessary

**Comment by WarpWing** [comment]
You just noticed this now? ggwp. I'm just having funnnnn. Also shouldn't Lea get involved because its SkyLea or she not doing bug reports too?

**Comment by metalcupcake5** [comment]
Closing this because as of now, its very very hard to get exact stats
