### ISSUE TITLE
Essence Display under catacombs

### ISSUE THREAD

**Issue by Artinator11** [SkyCryptWebsite/SkyCrypt#314]
Make it so that under the dungeon tab we can see how much essence the player has collected. Like say under dungeons, above Catacombs, there would be a list and the amount next to the name

- Ice Essence: 13 
- Wither Essence: 635

**Comment by metalcupcake5** [comment]
Unfortunately this data is not in the API at this time, so there is no way for us to display it

**Comment by Artinator11** [comment]
F

**Comment by metalcupcake5** [comment]
essence is now in api - reopening
