### ISSUE TITLE
Cannot click on items

### ISSUE THREAD

**Issue by haydenmfu** [SkyCryptWebsite/SkyCrypt#315]
**Describe the bug**
In the past, I used to be able to click/hover on items to get a preview of what it is. (could just be my end but this has been an issue for over a week now)

**Profile/Location**
All profiles

**Additional Info**
None

**Expected behavior**
Hover over the item and see a preview of the item name and stats.

**Screenshots**
I am jitter clicking on the winter rod for example
![image](https://user-images.githubusercontent.com/37965038/110229752-87143080-7ec0-11eb-9217-23a937684f1d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10?
 - Browser Chrome
 - Version 10?

**Additional context**

**Comment by metalcupcake5** [comment]
@nstringham

**Comment by metalcupcake5** [comment]
Usually its a problem with an outdated browser version, do you have the latest version of chrome?

**Comment by nstringham** [comment]
@haydenmfu Like metal said sometimes that happens when you have an outdated version of chrome can you put `chrome://settings/help` in the url bar and tell us what version of chrome it says you have

**Comment by haydenmfu** [comment]
Thank you, I wasn't aware that chrome was behind in updates because there was no 'update' symbol in the top right corner, it works now.
