### ISSUE TITLE
SkyCrypt's Bazaar API shows Russian for Acacia Wood

### ISSUE THREAD

**Issue by MySixSenses** [SkyCryptWebsite/SkyCrypt#317]
**Describe the bug**
The Bazaar API shows Акация instead of Acacia Wood
**Location**
https://sky.shiiyu.moe/api/bazaar

**Expected behavior**
It shows Acacia Wood
**Screenshots**
![image](https://user-images.githubusercontent.com/66916362/110276172-6f53af80-7f87-11eb-86db-e3ea0750222b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge

**Comment by nstringham** [comment]
This is not an issue with SkyCrypt it's a problem with an external resource
