### ISSUE TITLE
SC Chance figure not updating on rod switch

### ISSUE THREAD

**Issue by Pugzy** [SkyCryptWebsite/SkyCrypt#336]
**Describe the bug**
Fishing sea creature catch chance no longer updated (in the fishing section) when selecting different rods.
It is updated at the head of the page, however not in that section, these two share the same data stat tag only the former is updated.

![image](https://user-images.githubusercontent.com/8608892/111071052-4cb42000-84cc-11eb-80ab-73d6d135857b.png)

A recent commit https://github.com/SkyCryptWebsite/SkyCrypt/commit/8335d0f7dda251e902b9e9c8884060478c91ebf1#diff-cc124a01577ed15df124f49ac790d4d785e8c06f5e1379405d7e65e45f365dcdL637 breaks the fishing SC chance figure. The old anime library used the `targets: ...` and would allow the updating/animation of all matching elements, the new implementation using `flashForUpdate` only targets the first instance `element.innerHTML` (the one at the top of the page).

**Profile/Location**
https://sky.shiiyu.moe/stats/Pugzy/Pear skills section then fishing.

**Expected behavior**
The figure should be updated in both locations see https://sky.lea.moe/stats/Pugzy/Pear for example.

**Comment by nstringham** [comment]
I'll fix this
