### ISSUE TITLE
Fix the installation guide

### ISSUE THREAD

**Issue by GodSaveTheDoge** [SkyCryptWebsite/SkyCrypt#368]
**Describe the bug**
_Now open credentials.json_
Where? Which credentials.json?
Why is there a docker file? Trying to build it of course fails since I redis (/mongodb) isn't installed in the container.

**Error Log**
https://nekobin.com/silivedesa

**Developer Tools**
 - OS: Debian 10

**Comment by GodSaveTheDoge** [comment]
On an unrelated note: why does CODE_OF_CONDUCT.md have the exec bit set (same applies to logo.gvdesign, README.md, LICENSE)?

**Comment by nstringham** [comment]
running `npm i` should create a `credentials.json` in the root. if I remember correctly

**Comment by GodSaveTheDoge** [comment]
yes, after installing mongodb and redis it worked and i noticed that...

**Comment by GodSaveTheDoge** [comment]
this bodge seems to work:
```
FROM node:buster
RUN mkdir -p /usr/src/app
WORKDIR '/usr/src/app'
COPY . /usr/src/app
# Install mongodb
RUN apt install gnupg
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN apt update
RUN apt install -y mongodb-org
RUN mkdir -p /data/db
# Install redis
RUN apt install -y redis-server
# Run it
CMD ["bash", "-c", "(nohup redis-server &> /dev/null &) && (nohup mongod &> /dev/null &) && (npm i) && (npm start)"]
```

**Comment by metalcupcake5** [comment]
dockerfile isn't supported since none of us use(or know how to use) docker

**Comment by metalcupcake5** [comment]
I don't see how "Now open `credentials.json` is confusing though?

**Comment by GodSaveTheDoge** [comment]
that's because I was writing the Dockerfile (thus i didn't run npm i and noticed it only later when I ran bash in the container to check a few things).

**Comment by GodSaveTheDoge** [comment]
I'd add docker support but it's a pain in the ass to say the least. Having a config file would make changing stuff much easier (like the port, the redis host, the mongodb host...).

**Comment by nstringham** [comment]
I believe there was some work done already in an attempt to dockerize SkyCrypt but I don't think the project was ever finished

**Comment by GodSaveTheDoge** [comment]
I could easily do it if I could change the redis / mongod host and the port ig.
