### ISSUE TITLE
VIP+ Plus wrong color

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#371]
**Describe the bug**
in game VIP+ has a gold (`§6`) plus but on SkyCrypt it is green (`§a`)

**Profile/Location**
[Cookie_Wookie_7](https://sky.shiiyu.moe/stats/Cookie_Wookie_7)

**Expected behavior**
color on SkyCrypt matches color in game

**Screenshots**
![2021-04-04_15 59 19](https://user-images.githubusercontent.com/44071655/113520231-a3f36080-955f-11eb-8d06-5302ff4774e0.png)
![image](https://user-images.githubusercontent.com/44071655/113520221-9938cb80-955f-11eb-83a5-8da3600de01a.png)

**Comment by MartinNemi03** [comment]
Wait, it wasn't gold? Alright, i never noticed that.

**Comment by nstringham** [comment]
This bug also affects [LeaPhant/skyblock-stats](https://github.com/LeaPhant/skyblock-stats)
