### ISSUE TITLE
Last updated unknown timezone

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#384]
**Describe the bug**
It's unclear what time zone is used for the last updated stat hover

**Expected behavior**
SkyCrypt should either use the user's timezone or label what timezone is being used

**Screenshots**
![Screenshot_20210409-123343](https://user-images.githubusercontent.com/44071655/114212694-1d100080-9930-11eb-8485-59d7860aa8b9.jpg)

Android 10 Chrome 89

**Comment by MartinNemi03** [comment]
**Possible solution:** Removing current time processing from backend and adding it to the frontend.

**Comment by nstringham** [comment]
I am also going to add some localization because Americans don't understand what `5 March 14:00` is they want `March 5 2:00 PM`
