### ISSUE TITLE
Loving reforge ability damage not calculated

### ISSUE THREAD

**Issue by Artinator11** [SkyCryptWebsite/SkyCrypt#402]
**Describe the bug**
The Website is saying that I have 80% ability damage, 20 from enchanting level and 60 from shadow goggles

**Profile/Location**
https://sky.shiiyu.moe/stats/Artinator11/Papaya#Armor

**Additional Info**
I was using shadow goggles and 3/4's Necro Lord, with Chestplate on loving

**Expected behaviour**
For the ability damage to be added up correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/71243393/114865359-79de5000-9e35-11eb-9f95-bc91c382e7d4.png)
![image](https://user-images.githubusercontent.com/71243393/114865397-8793d580-9e35-11eb-84c4-7bbab652b0c5.png)
![image](https://user-images.githubusercontent.com/71243393/114865490-a4300d80-9e35-11eb-91c8-5e187a59df39.png)
![image](https://user-images.githubusercontent.com/71243393/114865505-af833900-9e35-11eb-8a8c-318125f85c97.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 10

**Comment by metalcupcake5** [comment]
does loving multiply total ability damage? and does it show up on the stats list?

**Comment by Artinator11** [comment]
Loving just adds 5 ability damage
