### ISSUE TITLE
Opt out of floc

### ISSUE THREAD

**Issue by GodSaveTheDoge** [SkyCryptWebsite/SkyCrypt#411]
**Is your suggestion related to a problem? Please describe in detail.**
Tracking. Floc to be specific. 

**Describe your suggestion**
Chrome is rolling out (it's already a thing, it's not far, right now it's just testing) floc. To be concise chrome will look at your history and, from that, it'll generate the floc id which will identify you in a group of users interested in the same things (note that this is just to be concise, there is a lot more about floc). You don't need to be too smart to understand that this is *so f\*\*\*ing bad I can't even put it into words*.
Luckly websites can opt out of floc (thus they won't be used to generate the id) by setting the "Permissions-Policy" header to "interest-cohort=()". 

**Describe alternatives you've considered**
Switch to any other browser (*fr, why are people even using chrome, it's so bad*). 

**Additional context**
See [eff.org article](https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea) if you want to know more about floc.
Note that this might impact chrome forks as well (brave is going to remove it as an example but some other forks might not).

**Comment by nstringham** [comment]
I don't think floc is all bad as you seem to think it is. It allows advertisers to serve effective ads without the need for everyone and their dog to know all your personal details. I think skycrypt should wait until floc has been more widely rolled out and the under informed media stops overeating before we make a decision about this.

**Comment by GodSaveTheDoge** [comment]
>I don't think floc is all bad as you seem to think it is. It allows advertisers to serve effective ads without the need for everyone and their dog to know all your personal details. I think skycrypt should wait until floc has been more widely rolled out and the under informed media stops overeating before we make a decision about this.

The issue is that it doesn't do that. Floc does **nothing** to stop fingerprinting, in fact it achieves the exact opposite: instead of trying to stop trackers or giving them less info, it gives even more data to use to calculate a fingerprint!
Do you really think ad networks will stop tracking users just because of floc? What about Firefox users? Brave? 
According to [Wikipedia](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers) ([this](https://upload.wikimedia.org/wikipedia/commons/e/ea/StatCounter-browser-ww-monthly-202011-202011-bar.png)) chome holds less than 64% of users. What about the other 37%?

**Comment by nstringham** [comment]
> The issue is that it doesn't do that. Floc does **nothing** to stop fingerprinting, in fact it achieves the exact opposite: instead of trying to stop trackers or giving them less info, it gives even more data to use to calculate a fingerprint!

yes floc currently adds more tracking surface area but floc is part of google's plan to deprecate 3rd party cookies which will drastically improve privacy on the web.

> Do you really think ad networks will stop tracking users just because of floc?

when they don't have 3rd party cookies in chrome they will not be able to track users as easily. and floc is an easy alternative.

> According to [Wikipedia](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers) ([this](https://upload.wikimedia.org/wikipedia/commons/e/ea/StatCounter-browser-ww-monthly-202011-202011-bar.png)) chome holds less than 64% of users. What about the other 37%?

it seems likely that other browsers will be interested in replacing 3rd party cookies even if they don't end up using floc specifically.

**Comment by GodSaveTheDoge** [comment]
>when they don't have 3rd party cookies in chrome they will not be able to track users as easily
You can already turn them off -.-
Firefox changed how 3rd party cookies work with the latest release too... You don't need to add floc to stop tracking, you can just... do it. (mind you I'm typing this from a Firefox profile with 3rd party cookies completely disabled and no floc)

**Comment by nstringham** [comment]
Yes **you** can just turn off 3rd party cookies. Unfortunately a lot of the internet today relies on targeted advertising to stay free. Google believes but simply turning off 3rd pretty cookies for all chrome users would be irresponsible and permanently damage the thriving ecosystem of free services on the web.

Hopefully someday there will be a way for server owners to cover the cost of their service without requiring their users to pay to use their website That doesn't involve tracking the user. That day is not today. Floc allows websites to continue making money the way they currently do without invading the user's privacy as much.

**Comment by nstringham** [comment]
Google has delayed floc rollout until late 2022. we can reassess the situation when the time comes
