### ISSUE TITLE
TypeError: Cannot read property "tier" of undefined

### ISSUE THREAD

**Issue by LuckyLMJ** [SkyCryptWebsite/SkyCrypt#429]
**Describe the bug**
A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).

When I search up my username (LuckyLMJ) on the website, it displays the above error: "TypeError: Cannot read property "tier" of undefined".

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)
https://sky.shiiyu.moe/stats/LuckyLMJ/Blueberry

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
I expected to view my skyblock stats.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari]  Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by boblovespi** [comment]
can i have a screenshot of your pig with the new pet item on it?

**Comment by metalcupcake5** [comment]
fixed in #430
