### ISSUE TITLE
Zombie pet Living Dead ability is messed up

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#446]
[petStats.js:1829-1844](https://github.com/SkyCryptWebsite/SkyCrypt/blob/master/src/constants/petStats.js#L1829-L1844) is very broken

**Comment by nstringham** [comment]
@dukio you've done a lot with pets do you think you can fix this?

**Comment by metalcupcake5** [comment]
How does it break?

**Comment by nstringham** [comment]
> How does it break?

I haven't tested this on a profile but the code looks really messed up. Here are some problems I noticed:
- The variable `mult` is used but never declared.
- According to the description it should be a personage increase (multiplicative) but the code is additive
- According to the description it should effect "all undead armor” but the code appears only to target zombie armor

**Comment by dukio** [comment]
I'll give it a better look later, but a few things I already noticed:
- `mult` should be 0.2 as per the third() perk, just need to copy/paste the constant
- it should apply to Zombie Armor, Revenant Armor, Reaper Armor (to check!), Reaper Mask
