### ISSUE TITLE
Item hover tooltips

### ISSUE THREAD

**Issue by ronaldgameking** [SkyCryptWebsite/SkyCrypt#461]
**Describe the bug**
A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).
Item tooltips have the item of the last thing you looked at or  other ways. And also showing item twice different rarity but I don't have one of that rarity.
**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)
https://sky.shiiyu.moe/stats/ronaldgameking/Raspberry
**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.

**Expected behavior**
It should display the correct item's tooltip.
**Screenshots**
![image](https://user-images.githubusercontent.com/21692337/118992872-5010cf80-b985-11eb-957e-3048525b6284.png)
![image](https://user-images.githubusercontent.com/21692337/118992907-58690a80-b985-11eb-907b-27d87570ab79.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 88.0.1
*(can we take a moment that the OS example for Desktop is 'iOS', which is not a desktop OS)*
**Additional context**

**Comment by nstringham** [comment]
This should be fixed by #459
