### ISSUE TITLE
Griffin pet info not filled in yet

### ISSUE THREAD

**Issue by CrushingStar** [SkyCryptWebsite/SkyCrypt#47]
I don't know if its already been reported but the new griffin pet has no data on the website. Hope you fill it in soon!
![griffin](https://user-images.githubusercontent.com/69564686/92795147-27f4b980-f37e-11ea-8c01-b4716dd904fd.JPG)

**Comment by WarpWing** [comment]
@boblovespi  and @metalcupcake5  do ur thing

**Comment by MartinNemi03** [comment]
Already working on it. Right now i'm making sure, that it has the correct values.

**Comment by boblovespi** [comment]
closed with https://github.com/SkyCryptWebsite/SkyCrypt/commit/52a04d145c81e71a51ec6bebb3238b003930b6fc
