### ISSUE TITLE
Add the master mode completion counts onto the boss collection counters.

### ISSUE THREAD

**Issue by REALDaGong** [SkyCryptWebsite/SkyCrypt#506]
**Is your suggestion related to a problem? Please describe in detail.**
In the current website state, master mode completions are not being counted into the total boss collection. Meanwhile, in-game, they are sharing the same collection bar.

**Describe your suggestion**
Add normal completions and master completions together, showing the final result to replace the current one. And show the separate completion counts at the top of 'claimed items' tippy or somewhere else.

**Current Website**
![image](https://user-images.githubusercontent.com/33593213/121781105-d9f33780-cbd5-11eb-9f2d-9245ed66b8e2.png)
**Current In-game Menu**
![image](https://user-images.githubusercontent.com/33593213/121781206-440bdc80-cbd6-11eb-92dd-1ec3d4f9b935.png)

**Comment by nstringham** [comment]
I don't know about this specifically but a lot of master mode stuff isn't in the API.

Does someone know if what is being suggested here is possible with the current API?

**Comment by REALDaGong** [comment]
It doesn't exist in `calculated.dungeons.boss_collections`, which actually has to be calculated manually from both `floors[id].stats`.

This does be kind of strange that they don't contain this into total kills in API, but in-game they count.

**Comment by MartinNemi03** [comment]
This should be added now with the latest commit. Let me know if there are any issues connected with it.
`https://github.com/SkyCryptWebsite/SkyCrypt/commit/63c445c495754c28639f7ea79ead8d34cf3705e7`
