### ISSUE TITLE
The API is protected by CloudFlare!

### ISSUE THREAD

**Issue by xernphoton** [SkyCryptWebsite/SkyCrypt#566]
**Describe the bug**
Attempting to access the v2 API through python requests gives me the cloudflare challenge page. This is probably not intended behaviour!

**Profile/Location**
https://sky.shiiyu.moe/api/v2/

**Additional Info**
none

**Expected behavior**
Getting the API data.

**Screenshots**

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by nstringham** [comment]
@MartinNemi03

**Comment by dukio** [comment]
Just out of curiosity did you try changing your UA?

**Comment by xernphoton** [comment]
no

**Comment by nstringham** [comment]
@xernphoton is this still an issue?

**Comment by DuckySoLucky** [comment]
@metalcupcake5
