### ISSUE TITLE
Multiple enderchest pages breaks the category buttons at the top

### ISSUE THREAD

**Issue by jojohnathon** [SkyCryptWebsite/SkyCrypt#58]
**Describe the bug**
When I look at the enderchest page of refraction's inventory, it stretches out the page by a lot.

**Profile/Location**
https://sky.shiiyu.moe/stats/Refraction/Apple

**Expected behavior**
When I click on fishing, it just brings me down to the enderchest section.

**Screenshots**
![image](https://user-images.githubusercontent.com/59942144/93038820-d2791080-f5fa-11ea-9aba-411e11542a7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: idk

**Comment by metalcupcake5** [comment]
Yep, I've noticed this. We may get around to having a list of enderchest pages, but odds are it'll be a long time before that happens unfortunately. Thanks for the report, we will try to get to fixing it ASAP
(_Also why is the screenshot of skylea_)

**Comment by jojohnathon** [comment]
Ok, thanks.
(_I changed the theme_)

**Comment by WarpWing** [comment]
Since this issue is a ongoing but not fixable as of now, I will close this.
