### ISSUE TITLE
Add Golden Dragon Pet

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#619]
player who has it: [ethu](https://sky.shiiyu.moe/stats/Ethu/Tomato#Pets)

**Comment by dukio** [comment]
Player who has it: https://sky.shiiyu.moe/stats/ChayUwU/Orange

If level < 100:
- Name: Golden Dragon Egg
- Skin: (fetching...)

If level >= 100
- Name: Golden Dragon
- Skin: https://sky.shiiyu.moe/head/2e9f9b1fc014166cb46a093e5349b2bf6edd201b680d62e48dbf3af9b0459116
