### ISSUE TITLE
Add a small square representing the color near the HEX color of leather armor

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#654]
Currently the color of a leather armor piece is displayed in the lore like this:
![image](https://user-images.githubusercontent.com/2744227/126568336-3fce88fa-629b-4af6-bcda-b41e3cbab2d9.png)

I think it would be really nice if we added a small square next to it with background-color the color of the armor.

**Comment by nstringham** [comment]
Is this really worth the added complexity? couldn't someone who really cared about the leather color just switch to the vanilla pack

**Comment by dukio** [comment]
If we handle this we will do it together with armor dyes, so closing this in favor of #1169
