### ISSUE TITLE
Add axes to farming hoes section

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#657]
some items such as the Pumpkin Dicer are not hoes but should be included in the farming hoes section

this section should probably also be renamed to farming tools

**Comment by dukio** [comment]
Section gets renamed in #1193 

Still need to figure out how to add Pumpkin Dicer and Melon Dicer, probably need a way to hardcode id to categories

**Comment by dukio** [comment]
I'll assign this to myself but it needs to be done after #1193 is merged

**Comment by DuckySoLucky** [comment]
@metalcupcake5 added in https://github.com/SkyCryptWebsite/SkyCrypt/pull/1885
