### ISSUE TITLE
missing superboom texture for HQ13

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#663]
**Describe the bug**
int the Hypixel Skyblock Pack v13 pack the supperboom TNT uses the vanilla texure

**Profile/Location**
https://sky.shiiyu.moe/stats/Cookie_Wookie_7/Papaya#Inventory

**Actual behavior**
![image](https://user-images.githubusercontent.com/44071655/126861599-42c6dad7-21c6-4c2e-8768-f938ad7d8e15.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/44071655/126861593-36e773fb-e8e2-4260-9177-607bf52cb851.png)

**Comment by nstringham** [comment]
this is caused by the texture pack system being unable to handle 3d models

related to #743

**Comment by DuckySoLucky** [comment]
@metalcupcake5
