### ISSUE TITLE
TypeError: Cannot read property 'tag' of undefined

### ISSUE THREAD

**Issue by xernphoton** [SkyCryptWebsite/SkyCrypt#668]
**Describe the bug**
going to Cherr7's profile gives TypeError: Cannot read property 'tag' of undefined

**Profile/Location**
https://sky.shiiyu.moe/stats/Cherr7/Lemon

**Additional Info**
Rabbit Hat/Silverfish/Refined Stonk/Private Island

**Expected behavior**
View my profile

**Screenshots**
<img width="1440" alt="Screen Shot 2021-07-27 at 12 23 31 PM" src="https://user-images.githubusercontent.com/70344800/127191074-7d33793b-0572-4ac3-8fe9-effe6df736bb.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version Latest as of 7/27/2021

**Comment by nstringham** [comment]
This might have been broken in #650 I'll take a closer look when I get a chance

**Comment by nstringham** [comment]
This bug also edfects https://sky.shiiyu.moe/stats/cerebruhm and https://sky.shiiyu.moe/stats/Tocye/Raspberry

**Comment by FreakyDj** [comment]
I am affected too. https://sky.shiiyu.moe/stats/FreakyDj/Strawberry
