### ISSUE TITLE
Bonuses in wrong order

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#715]
https://github.com/SkyCryptWebsite/SkyCrypt/pull/699/commits/202da61c9d83c3f3cfd7419803f38d0a234c1dd7 put the stats in alphabetical order Wich makes bonuses now in the wrong order

**Comment by nstringham** [comment]
@dukio

**Comment by dukio** [comment]
😞

**Comment by metalcupcake5** [comment]
fixed with 85834166ab7db481ff1a7901e2b1c7aadebeafeb (i hope)
