### ISSUE TITLE
Floor 7 armor textures.

### ISSUE THREAD

**Issue by CoderBoyo** [SkyCryptWebsite/SkyCrypt#734]
**Describe the bug**
I think that all the f7 armor textures got screwed up.

**Profile/Location**
Literally look at any profile that has f7 armor. 
(Necron, storm etc)

**Comment by nstringham** [comment]
Similar issue reported on discord https://discord.com/channels/738971489411399761/738990246825427084/875394027611115520

**Comment by nstringham** [comment]
Can someone check whether this issue affects all packs or just some of them

**Comment by CoderBoyo** [comment]
> Can someone check whether this issue affects all packs or just some of them

The issue seems to be with only FurfSky Reborn v1.4 and Hypixel Skyblock Pack v13

**Comment by dukio** [comment]
@nstringham this seems the same issue as #404, which should get fixed by #949 ... correct?

**Comment by nstringham** [comment]
> @nstringham this seems the same issue as #404, which should get fixed by #949 ... correct?

yes this seams to be the same as #404 I'm not sure if #949 would fix it I haven't looked at that PR very closely

**Comment by nstringham** [comment]
oops didn't mean to close it

**Comment by nstringham** [comment]
actually this should probobly be closed as a duplicate of #404
