### ISSUE TITLE
FurfSky custom pet skins are displayed as skin texture instead of rendered head

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#743]
**Describe the bug**
With FurfSky pet skins are displayed as skin texture instead of rendered 3d heads.

**Profile/Location**
https://sky.shiiyu.moe/stats/dukioooo/Pomegranate#Inventory (Inventory -> Storage -> Yellow and Lime backpacks)

**Screenshots**
![image](https://user-images.githubusercontent.com/2744227/129982977-063960e8-da03-439f-b890-3e533e3ed641.png)

Original report (profile no longer has the broken pets in storage):
![image](https://user-images.githubusercontent.com/2744227/129983042-2cd62e2a-2939-40b3-ba9e-2c9033a39b12.png)

**Comment by MartinNemi03** [comment]
I'll remove them for now, so they don't cause problems as we don't have support for custom models. 
They'll default to their vanilla textures.
