### ISSUE TITLE
Pack Problem (Hypixel Skyblock Pack v12)

### ISSUE THREAD

**Issue by Nisutec** [SkyCryptWebsite/SkyCrypt#76]
**Describe the bug**
When I use the Pack `Hypixel Skyblock Pack v12 - 16x` or `Hypixel Skyblock Pack v12 - 32x` the armor textures are not displayed on the website.

**Profile/Location**
https://sky.shiiyu.moe/stats/Nisutec/Pear

**Additional Info**
I have tried the `Superior Dragon Armor` and the `Perfect Armor - Tier XII` to display the problem.

**Expected behavior**
The Website displays the right textures for the armor.

**Screenshots**
<details>
  <summary>Superior Dragon Armor</summary>
  
  ![Superior Dragon Armor Website](https://p52.p0.n0.cdn.getcloudapp.com/items/KouwzORk/Image%202020-09-27%20at%209.46.06%20AM.png?v=dc7fd42d0f3e5f7f3f29ef84b63703f1)
  ![Superior Dragon Armor Ingame](https://p52.p0.n0.cdn.getcloudapp.com/items/wbuP1ZOj/Image%202020-09-27%20at%209.41.32%20AM.png?v=2c2dbb3347cdf6a603de903af721ee22)
</details>

<details>
  <summary>Perfect Armor - Tier XII</summary>
  
  ![Perfect Armor - Tier XII Website](https://p52.p0.n0.cdn.getcloudapp.com/items/E0urW2N4/Image%202020-09-27%20at%209.44.09%20AM.png?v=413910380e7228c1ed42aaface1f10f1)
  ![Perfect Armor - Tier XII Ingame](https://p52.p0.n0.cdn.getcloudapp.com/items/E0urW2NW/Image%202020-09-27%20at%209.42.01%20AM.png?v=cc9fc135f9cea2d867355f5c2e7c235e)
</details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 81

**Comment by WarpWing** [comment]
This is a known issue. It's being worked on.

**Comment by metalcupcake5** [comment]
As warp said, known issue, working on it

**Comment by WarpWing** [comment]
I'm sure the Dev Team appreciate the report though :D

**Comment by metalcupcake5** [comment]
Fixed with https://github.com/SkyCryptWebsite/SkyCrypt/commit/c1ee508febd2357fe5eade66e272477edd2d81bf

**Comment by WarpWing** [comment]
Yay, the long awaited anime has closed. Season 2 @metalcupcake5  ?

**Comment by metalcupcake5** [comment]
![image](https://user-images.githubusercontent.com/43897385/101545479-28d8bf80-395c-11eb-93b8-7861bb812b40.png)

**Comment by WarpWing** [comment]
I feel it in the force Metal-Chan @metalcupcake5  ;)
