### ISSUE TITLE
indicator for pets with skins equipped

### ISSUE THREAD

**Issue by JSanchoG** [SkyCryptWebsite/SkyCrypt#788]
i think this doesnt need any explanation

![Image](https://i.imgur.com/WQca9wY.png)
this white thing in left bottom of a pet:
`background-image: linear-gradient(to bottom left,transparent 0 92.5%,#fff 90% 100%);`

outline box shadow (legendary wolf pet as example):
`box-shadow: 0px 0px 7.5px 2px rgb(255 255 255 / 80%);`
inside box shadow (epic baby yeti as example):
`box-shadow: inset 0px 0px 7.5px 2px rgb(255 255 255 / 80%);`

**Comment by JSanchoG** [comment]
or any other indicator idc if this gets includes, it would be cool to have an indicator that shows if the pet has a skin on or not

**Comment by nstringham** [comment]
I don't think this is necessary because you can just look at the displayed skin and if you are unsure you can check the lore
![image](https://user-images.githubusercontent.com/44071655/132030097-f2d2cef8-9116-4e99-a8a1-92fe5cad8206.png)

**Comment by dukio** [comment]
> I don't think this is necessary because you can just look at the displayed skin and if you are unsure you can check the lore
> ![image](https://user-images.githubusercontent.com/44071655/132030097-f2d2cef8-9116-4e99-a8a1-92fe5cad8206.png)

also the  star in the name
![image](https://user-images.githubusercontent.com/2744227/132030347-9bff8044-be24-448c-b674-b2da7986a0a9.png)

**Comment by nstringham** [comment]
> also the star in the name
> ![image](https://user-images.githubusercontent.com/2744227/132030347-9bff8044-be24-448c-b674-b2da7986a0a9.png)

oh cool I didn't know that

**Comment by JSanchoG** [comment]
but still, if u go on someones profile with 200 useless pets and miss like one common lvl 100 jerry with some hella expensive skin (people selling all their stuff in SBZ trading channel pretty often)

**Comment by dukio** [comment]
> but still, if u go on someones profile with 200 useless pets and miss like one common lvl 100 jerry with some hella expensive skin (people selling all their stuff in SBZ trading channel pretty often)

That seems like an edge case, and if you are trading for Hella expensive skins I think you should already know which texture every skin has...


Either way, the box shadow is too far from the overall design of the website, so I wouldn't do that for sure

For the corner, now it's used for recomb items so it has another meaning (even though it's in a different position). Also I don't think it represent what it means, almost noone will understand it means that it's an item with custom skin.


We could think of something else, but I don't really see it as something urgent/important.

**Comment by JSanchoG** [comment]
> > but still, if u go on someones profile with 200 useless pets and miss like one common lvl 100 jerry with some hella expensive skin (people selling all their stuff in SBZ trading channel pretty often)
> 
> That seems like an edge case, and if you are trading for Hella expensive skins I think you should already know which texture every skin has...
> 
> Either way, the box shadow is too far from the overall design of the website, so I wouldn't do that for sure
> 
> For the corner, now it's used for recomb items so it has another meaning (even though it's in a different position). Also I don't think it represent what it means, almost noone will understand it means that it's an item with custom skin.
> 
> We could think of something else, but I don't really see it as something urgent/important.

ye i just wanted to ask for some indicator those were just 2 examples (the idea was the whole concept of indicating if pet has the skin on, examples were just to show what i mean by the pet skin indicator), it doesnt seem important when compared to recombs, but it would be cool

**Comment by JSanchoG** [comment]
and also got this just sitting on my screen
![Przechwytywanie](https://user-images.githubusercontent.com/70905916/132067975-8b67fbaa-8d69-4f38-88fc-563ed38c2c22.PNG)
https://pastebin.com/raw/PXKYmnHx

**Comment by nstringham** [comment]
> and also got this just sitting on my screen
> ![Przechwytywanie](https://user-images.githubusercontent.com/70905916/132067975-8b67fbaa-8d69-4f38-88fc-563ed38c2c22.PNG)
> https://pastebin.com/raw/PXKYmnHx
> EDIT: dont mind the lvl thing, just wanted to show this off as the indicator to anything that could be included later

I'm not really a big fan of using a light colored drop shadow I think it looks unnatural and distracting
