### ISSUE TITLE
Upcoming new rarity: Divine

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#799]
Ref: https://hypixel.net/threads/psa-upcoming-gemstone-changes.4523454/page-16#post-32716374

> 1/ The rarity change on the Divan's Drill was uncalled for, so the default rarity will remain Mythic.
> However, we will officialize a rarity above Mythic, called Divine, with its own reforge stats. This rarity will be kept exclusive to items of the caliber of the Divan’s Drill.
> Divine will be added as an AH filter.
> Enchanted Books cannot be Divine.

**Comment by nstringham** [comment]
looks like it is using `§4`
https://hypixel.net/threads/first-look-at-divine-rarity.4537274/

**Comment by dukio** [comment]
Same as supreme, gotta watch out! (might need something like special and very special)

**Comment by nstringham** [comment]
> Same as supreme, gotta watch out! (might need something like special and very special)

what do special and very special need?

**Comment by dukio** [comment]
> > Same as supreme, gotta watch out! (might need something like special and very special)
> 
> what do special and very special need?

They use both the same color (light red, §c iirc), so in the function that gets the rarity there's an extra check if the string starts with VERY, then it's Very Special, otherwise it's special. We will have to do something similar here to handle both DIVINE and SUPREME (they are both dark red)

That function is the same that causes missing rarity when an item lore doesn't end with "LEGENDARY SWORD" but instead like "Sell for 3 coins" or something else, example:
![image](https://user-images.githubusercontent.com/2744227/132901538-b1b7fb0e-771d-45db-b720-d06b23aeeacf.png)
(a used had this issue a couple days ago)

I was working on a possible update using regex instead but I couldn't finish it (I'm also not really expert with regex, here's what I was doing (unfinished): https://regex101.com/r/N38J2G/1)

**Comment by nstringham** [comment]
I think the reason that we were using the color code in the first place was to check for rarity on non-English lore. I would suggest as a solution to look for the English word first and then if we can't find it fall back to using the color.

**Comment by dukio** [comment]
> I think the reason that we were using the color code in the first place was to check for rarity on non-English lore. I would suggest as a solution to look for the English word first and then if we can't find it fall back to using the color.

I totally forgot about non-english lore, that's a good solution
