### ISSUE TITLE
Wardrobe's armor not showing

### ISSUE THREAD

**Issue by Brandonion** [SkyCryptWebsite/SkyCrypt#80]
**Describe the bug**
I put my Strong Dragon armour in my wardrobe, but for some reason, it doesn't show up in SkyCrypt

**Profile/Location**
https://sky.shiiyu.moe/stats/Brandonion99/Papaya

**Additional Info**
I have tried taking my armour out and putting it back in but doesn't work. I have also put other armour in the wardrobe and it showed in Skycrypt

**Comment by metalcupcake5** [comment]
I'll take a look at this soon
*2-3 hours of submission totally*

**Comment by WarpWing** [comment]
@Brandonion how long did you take it in and out for? API Updating isn't instant. I believe it updates when you log in/out but yeah.

**Comment by Brandonion** [comment]
> @Brandonion how long did you take it in and out for? API Updating isn't instant. I believe it updates when you log in/out but yeah.

I took it out for like a second, but the armor's been in the wardrope for like a month

**Comment by WarpWing** [comment]
@Brandonion  is it still in the wardrobe now? Make sure it is when you respond to me. I have Github Notifs on Standby so ill see it

**Comment by Brandonion** [comment]
No, It's still not in.

**Comment by Pottedplant530** [comment]
It appears the problem has been resolved?

**Comment by nstringham** [comment]
@Brandonion is this still broken?

Also the link to your profile is broken can you post a new one?

**Comment by Brandonion** [comment]
> @Brandonion is this still broken?
> 
> Also the link to your profile is broken can you post a new one?

Its fixed now

**Comment by WarpWing** [comment]
Finally, I got the anime ending this PR deserved.
