### ISSUE TITLE
constant > misc.js > item_types should include all the new types? 

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#817]
I noticed that https://github.com/SkyCryptWebsite/SkyCrypt/blob/0f97deca5d09257cc5520f6239c5c264c612f634/src/constants/misc.js#L7-L21 is missing a lof of types:
- Gauntlet
- Dungeon ...everything (helmet boots sword bow rod...)
- Fishing Weapon
- probably more I can't think of right now

Should this get updated?

**Comment by metalcupcake5** [comment]
Where is the array used?

**Comment by metalcupcake5** [comment]
https://github.com/SkyCryptWebsite/SkyCrypt/blob/fc916eef4eb8d7a11be174bd051769f786e870b3/src/lib.js#L845
forgot i could search, this line is the only line it's used in
