### ISSUE TITLE
CD

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#889]
Restarting the site seems to be quite a bit of work and sometimes doesn't get done so I would like to propose a continuous deployment system.

Rename master to dev
Dev should continuously deploy to cupcake.shiiyu
Create a new branch called main
Main should continuously deploy to sky.shiiyu

All PRs would be made to dev so that they can be tested in a production environment before being deployed to sky

**Comment by WarpWing** [comment]
Your mom is a continuous deployment system 😳😳

**Comment by nstringham** [comment]
I thought about it some more and I think it might be better to call the production branch "production"  instead of "main"
