### ISSUE TITLE
Constantly rate limited

### ISSUE THREAD

**Issue by RDIL** [SkyCryptWebsite/SkyCrypt#91]
Hi!

I personally am constantly being rate limited on the website due to the API key, so it might be worthwhile to have multiple, and cycle through them until one that isn't rate limited is found.  This would make the experience a lot easier for a lot of players.  

Thanks!

**Comment by metalcupcake5** [comment]
![image](https://user-images.githubusercontent.com/43897385/95110980-b0534980-06f3-11eb-9d12-fe73fff52d90.png)

**Comment by metalcupcake5** [comment]
We have no way to fix this other than waiting for hypixel to expand our key. We made an announcement in our discord, here it is if you haven't seen it.
![image](https://user-images.githubusercontent.com/43897385/95111122-e4c70580-06f3-11eb-9621-bc7fa49c2f5f.png)
