### ISSUE TITLE
Titanium Drill DR-X355 has incorrect forge times

### ISSUE THREAD

**Issue by fm-leonardo** [SkyCryptWebsite/SkyCrypt#922]
**Describe the bug**
Forge information for the Titanium Drill DR-X355 says it has finished forging 24 hours before its actual finishing time.

**Profile/Location**
https://sky.shiiyu.moe/stats/YoumuTouhou/Papaya#Skills

**Expected behavior**
It should show the actual time when the item should be ready, this is likely caused by the variable `TITANIUM_DRILL_1` having the wrong value in `/src/constants/forge.js` (should be `24 * 2 * 60 + 16 * 60` instead of `40 * 60`).

**Comment by dukio** [comment]
PR already done #921

**Comment by nstringham** [comment]
> PR already done #921

In general you should wait for the PR to be merged before closing issues

**Comment by dukio** [comment]
> > PR already done #921
> 
> In general you should wait for the PR to be merged before closing issues

you are indeed correct, idk why I closed it 🤔 woops
