### ISSUE TITLE
Add label for upcoming changes

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#924]
Add a new label (https://github.com/SkyCryptWebsite/SkyCrypt/labels) for issues of upcoming changes, example:
https://github.com/SkyCryptWebsite/SkyCrypt/issues/923https://github.com/SkyCryptWebsite/SkyCrypt/issues/923

This would help mark issues that are not required to be done right now but will be required when the next update releases. Useful to track things and not forget them.

**Comment by MartinNemi03** [comment]
Added the tag you requested, hope it looks good.
