### ISSUE TITLE
Android Firefox Nav Bar Broken

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#927]
**Describe the bug**
In firefox clicking on the nav bar goes to the top of the page instead of the correct section

**Profile/Location**
N/A

**Additional Info**
commenting out this line fixes it
https://github.com/SkyCryptWebsite/SkyCrypt/blob/16749bb096cb93b4214541100db9c04afad086c1/public/resources/scss/shared.scss#L2022

**OS and browser**
- Device: OnePlus 6
- OS: OxygenOS 11.1.1.1 (android 11)
- Browser Firefox stable
- Version 93.2.0

**Comment by DuckySoLucky** [comment]
https://github.com/SkyCryptWebsite/SkyCrypt/assets/75372052/d24f22a9-fb13-4a0a-91e9-b695c2557786

@metalcupcake5 works fine for me so most likely it got fixed :shrug:
