### ISSUE TITLE
experiment super pairs background is only 81px and not 100 like the rest

### ISSUE THREAD

**Issue by lochyj** [SkyCryptWebsite/SkyCrypt#929]
The experiments super pairs background is only 81px and not 100px like the rest of the cards in the experiments

**Comment by dukio** [comment]
I don't understand which background you are referring to, can you send a screenshot?

**Comment by lochyj** [comment]
![image](https://user-images.githubusercontent.com/79903111/140046932-a1eefa17-d2c1-4f02-944b-42a01ceed111.png)

**Comment by dukio** [comment]
@lochyj sorry but I keep on not understanding where the issue is... can you highlight it or explain better what the issue is?

**Comment by dukio** [comment]
Closing since author didn't reply
