### ISSUE TITLE
Newton Nether Warts Hoe using Reaper Scythe's Texture.

### ISSUE THREAD

**Issue by Arthurism** [SkyCryptWebsite/SkyCrypt#981]
**Describe the bug**
The title describes itself.

**Profile/Location**
https://sky.shiiyu.moe/stats/Arthurism/Orange#Inventory

**Additional Info**
Item is a Legendary Blessed Newton Nether Warts Hoe.

**Expected behavior**
It should show the actual texture of the Nether Warts Hoe.

**Screenshots**
![image](https://user-images.githubusercontent.com/80765214/142636302-8e6a0d9e-fb81-4850-b0ee-80fc5480920c.png)

**Desktop (please complete the following information):**

- OS: Windows 11 (Beta Channel)
- Browser Opera GX
- Version *idk*

**Smartphone (please complete the following information):**

- Device: -
- OS: -
- Browser -
- Version -

**Additional context**
None.

**Comment by metalcupcake5** [comment]
@dukio is working on this i believe

**Comment by nstringham** [comment]
related discussion on Discord
https://discord.com/channels/738971489411399761/911036781661679656/911513398745919498
