### ISSUE TITLE
Remove default pack

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#983]
We should remove the default pack and instead just let the user pick their desired resource pack...

Currently FurfSky Reborn is pretty much 95% of the items in the default pack anyway, the default pack doesn't make sense anymore. It was useful when no resource pack was covering all items, but now there's multiple packs which aim to cover all skyblock items so this doesn't really make sense anymore.

**Comment by Pottedplant530** [comment]
Not to mention how much this would clear up the discord of just people asking for the default pack then leaving

**Comment by DuckySoLucky** [comment]
@metalcupcake5
