### ISSUE TITLE
Default pack using RNBW+ instead of FSR for HotM... ignoring priority!?

### ISSUE THREAD

**Issue by dukio** [SkyCryptWebsite/SkyCrypt#991]
The default pack is using the RNBW+ texture for heart of the mountain, even though FurfSky Reborn also has HotM texture and the pack is higher priority than RNBW+...

It should use FSR textures instead of RNBW+...

**Comment by DuckySoLucky** [comment]
@metalcupcake5 FSR doesn't have HOTM textures anymore in it's folder so close this too
